# O que é análise de dados


Análise de dados é o processo de inspecionar, limpar, transformar e modelar dados com o objetivo de conseguir informações úteis e ajudar em tomadas de decisões.

Os passos da análise de dados são:

1.   Exatração de dados: utilizando geralmente, SQL, tabelas (excel, csv, etc...), scrapping.
2.   Limpeza de dados: Remover dados, tipos incorretos, valores inválidos ou incorretos, dados vazios ou não relevantes.
3.   Tratamento dos dados: reformatar, tranformar, lidar com dados categóricos e/ou hierárquicos, indexar, combinar, adicionar dados.
4.   Análise: Explorar, criar modelos estatísticos, criar vizualizações, representações, fazer relatórios.

Para isso utilizaremos python e algumas bibliotecas como pandas e matplotlib.

# Importando bibliotecas


*   Pandas -> tratar, filtrar dados
*   Matplotlib e Seaborn -> gráficos

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Series em pandas

Series é uma lista de dados indexados com uma só coluna, unidimensional.

# Criando Series

In [ ]:
s1 = pd.Series([0,1,2,3,4,5,6])
s2 = pd.Series([1.0,2,3,4,5,6])

s1

0    0
1    1
2    2
3    3
4    4
5    5
6    6
dtype: int64

In [ ]:
s1.values

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
s1.dtype

dtype('int64')

In [ ]:
s1.describe()

count    7.000000
mean     3.000000
std      2.160247
min      0.000000
25%      1.500000
50%      3.000000
75%      4.500000
max      6.000000
dtype: float64

# Selecionando valores em Series

In [ ]:
s1[1]

1

In [ ]:
s1.index

RangeIndex(start=0, stop=7, step=1)

In [ ]:
s1.index = ['a','b','c','d','e','f','g']

In [ ]:
s1.index

RangeIndex(start=0, stop=7, step=1)

In [ ]:
s1['a']

0

In [ ]:
s1[['a', 'b']]

a    0
b    1
dtype: int64

In [ ]:
s1.iloc[0]

0

In [ ]:
s1.iloc[[0, 1]]

a    0
b    1
dtype: int64

# Outras formas de se criar series

In [ ]:
# de um dicionario
s3 = pd.Series({'a':0,'b':1,'c':2,'d':3,'e':4,'f':5,'g':6})
# de uma lista, com o index explicito
s4 = pd.Series([0,1,2,3,4,5,6], index=['a','b','c','d','e','f','g'])
# de um numpy arange
s7 = pd.Series(np.arange(0,7), index=['a','b','c','d','e','f','g'])

# de um numpy array aleatorio 0~1
s5 = pd.Series(np.random.rand(7), index=['a','b','c','d','e','f','g'])
# de um numpy array aleatorio com numeros inteiros (0~9, 10 não incluso)
s6 = pd.Series(np.random.randint(0,10, 7), index=['a','b','c','d','e','f','g'])

s7

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

# Fatiamento e Operações

In [ ]:
# utilizando loc, usamos o nome do indice,
# ou, uma lista de indices, ou o primeiro
# e o ultimo a ser selecionado
s4.loc['a':'d']

a    0
b    1
c    2
d    3
dtype: int64

In [ ]:
# utilizando loc, o ultimo indice não será incluso
s4.iloc[0:3]

a    0
b    1
c    2
dtype: int64

In [ ]:
s4.loc['a':'d']/2

a    0.0
b    0.5
c    1.0
d    1.5
dtype: float64

# Seleção respeitando condições

In [ ]:
s3 > 3

a    False
b    False
c    False
d    False
e     True
f     True
g     True
dtype: bool

In [ ]:
s3.loc[s3 > 3]

e    4
f    5
g    6
dtype: int64

# Métodos estatísticos



*   mean -> Média
*   median -> Mediana
*   quantile( ) -> semelhante a mediana, encontra posições relativos a uma porcentagem de 0 a 1
*   std -> Desvio padrão
*   var -> Variância
*   np.log(series) -> Logarítimo

In [ ]:
s3.quantile(.5)

3.0

In [ ]:
np.log(s3)

/usr/local/lib/python3.7/dist-packages/pandas/core/arraylike.py:364: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

a        -inf
b    0.000000
c    0.693147
d    1.098612
e    1.386294
f    1.609438
g    1.791759
dtype: float64

In [ ]:
s3[s3 > 3].mean()

5.0

# Operadores booleanos



*   ~ not
*   | or
*   & and

Para operações booleanas, cada uma das condições deve estar entre parenteses

Ex : (s3 > 3) | (s3 < 2)

In [ ]:
# use o operador, colocando explicitamente [or] ou qualquer outro irá dar erro
# exemplo de erro

#s3[(s3 > 3) or (s3 < 2)]

In [ ]:
s3[(s3 > 3) | (s3 < 2)]

a    0
b    1
e    4
f    5
g    6
dtype: int64

# Modificando series

Até agora, apesar de tantas alterações, os dados não foram alterados definitivamente, pois os novos valores não foram atribuidos a nenhuma variavel.

In [ ]:
# modificando pelo nome do indice
s3['a'] = 33
s3.loc['b'] = 12

# modificando pelo numero do indice
s3.iloc[-1] = 12

# modificando a partir de uma condição

s3[s3 <= 4] = 3
s3

a    33
b    12
c     3
d     3
e     3
f     5
g    12
dtype: int64

In [ ]:
# s3, em todas as posições, recebe o valor 2
s3.loc[:] = 2
s3

a    2
b    2
c    2
d    2
e    2
f    2
g    2
dtype: int64

# DataFrames em pandas

Dataframes são dados em tabelas, diferente de series que são uma linha de dados.
Dataframes também podem ser criados de diversas maneiras.

In [ ]:
# Dataframes de um dicionario
df1 = pd.DataFrame({'numbers': [0, 1, 2, 3, 4, 5, 6],
                    'words': ['Eli Grant', 'triangle', 'integral', 'relating', 'altering', 'alerting', 'Langiert'],
                    'symbols': ['!', '@', '#', '$', '%', '¨', '&'],
                    'float':[.0,.1,.2,.3,.4,.5,.6]})

# Dataframes de listas de listas, cada lista é uma linha
df2 = pd.DataFrame([[0,'Eli Grant','!',.0], [1, 'triangle','@',.1], [2, 'integral','#',.2], [3,'relating','$',.3],
                    [4, 'altering','%',.4], [5,'alerting','¨',.5], [6, 'Langiert','&',.6]], columns=['numbers', 'words','symbols','float'])

# Dataframes de series, names se tornam os indices
s_index=['numbers', 'words','symbols','float']
s1 = pd.Series([0,'Eli Grant','!',.0], name=0, index=s_index)
s2 = pd.Series([1, 'triangle','@',.1], name=1, index=s_index)
s3 = pd.Series([2, 'integral','#',.2], name=2, index=s_index)
s4 = pd.Series([3,'relating','$',.3], name=3, index=s_index)
s5 = pd.Series([4, 'altering','%',.4], name=4, index=s_index)
s6 = pd.Series([5,'alerting','¨',.5], name=5, index=s_index)
s7 = pd.Series([6, 'Langiert','&',.6], name=6, index=s_index)
df3 = pd.DataFrame([s1,s2,s3,s4,s5,s6,s7])

# Concat, usando cada series como uma coluna, names se tornam o nome da coluna
s1 = pd.Series([0, 1, 2, 3, 4, 5, 6], name='numbers')
s2 = pd.Series(['Eli Grant', 'triangle', 'integral', 'relating', 'altering', 'alerting', 'Langiert'], name='words')
s3 = pd.Series(['!', '@', '#', '$', '%', '¨', '&'], name='symbols')
s4 = pd.Series([.0,.1,.2,.3,.4,.5,.6], name='float')
df4 = pd.concat([s1,s2,s3,s4], axis='columns')


df1

   numbers      words symbols  float
0        0  Eli Grant       !    0.0
1        1   triangle       @    0.1
2        2   integral       #    0.2
3        3   relating       $    0.3
4        4   altering       %    0.4
5        5   alerting       ¨    0.5
6        6   Langiert       &    0.6

# Fatiamento, selecão e indexação

In [ ]:
# semelhante ao Series podemos modificar o indice de um dataframe
df1.index = ['a','b','c','d','e','f','g']
df1

   numbers      words symbols  float
a        0  Eli Grant       !    0.0
b        1   triangle       @    0.1
c        2   integral       #    0.2
d        3   relating       $    0.3
e        4   altering       %    0.4
f        5   alerting       ¨    0.5
g        6   Langiert       &    0.6

In [ ]:
# Com o indice modificado, loc agora utiliza este novo indice, e retorna um series
# contendo a linha [c]
df1.loc['c']

numbers           2
words      integral
symbols           #
float           0.2
Name: c, dtype: object

In [ ]:
# Iloc para posições numericas dos indices
df1.iloc[3]

numbers           3
words      relating
symbols           $
float           0.3
Name: d, dtype: object

In [ ]:
# selecionando uma coluna
df1['numbers']

a    0
b    1
c    2
d    3
e    4
f    5
g    6
Name: numbers, dtype: int64

In [ ]:
# selecionando multiplas colunas
df1.loc[:, ['numbers', 'float']]

   numbers  float
a        0    0.0
b        1    0.1
c        2    0.2
d        3    0.3
e        4    0.4
f        5    0.5
g        6    0.6

In [ ]:
# seleção condicional
df1['numbers'] > 3

a    False
b    False
c    False
d    False
e     True
f     True
g     True
Name: numbers, dtype: bool

In [ ]:
# indices onde df1['numbers'] > 3 tem o valor True
df1.loc[df1['numbers'] > 3]

   numbers     words symbols  float
e        4  altering       %    0.4
f        5  alerting       ¨    0.5
g        6  Langiert       &    0.6

In [ ]:
# seleção de linhas com condição + seleção de colunas
df1.loc[df1['numbers'] > 3, ['words','symbols']]

      words symbols
e  altering       %
f  alerting       ¨
g  Langiert       &

# Deletando linhas e colunas

In [ ]:
# para linhas
df1.drop(['a','c','e'])

   numbers     words symbols  float
b        1  triangle       @    0.1
d        3  relating       $    0.3
f        5  alerting       ¨    0.5
g        6  Langiert       &    0.6

In [ ]:
# para colunas
df1.drop(['words','float'], axis='columns')
# ou
df1.drop(columns=['words', 'float'])

   numbers symbols
a        0       !
b        1       @
c        2       #
d        3       $
e        4       %
f        5       ¨
g        6       &

# Modificando dataFrames

Semelhante a series, um dataframe só sera modificado, caso a alteração seja atribuida a uma variavél, geralmente, a sua própria

Alguns métodos também possuem a opção inplace=True para não ser necessaria carregar a alteração em uma variável

adicionando uma coluna

In [ ]:
s8 = pd.Series(['+','-','^2'], index=['a','d','g'])

df1['signals'] = s8
df1

   numbers      words symbols  float signals
a        0  Eli Grant       !    0.0       +
b        1   triangle       @    0.1     NaN
c        2   integral       #    0.2     NaN
d        3   relating       $    0.3       -
e        4   altering       %    0.4     NaN
f        5   alerting       ¨    0.5     NaN
g        6   Langiert       &    0.6      ^2

adicionando uma linha

In [ ]:
s9 = pd.Series([7,'etcetera','*',.7], index=['numbers','words','symbols','float'])
df1.loc['h'] = s9
df1

   numbers      words symbols  float signals
a        0  Eli Grant       !    0.0       +
b        1   triangle       @    0.1     NaN
c        2   integral       #    0.2     NaN
d        3   relating       $    0.3       -
e        4   altering       %    0.4     NaN
f        5   alerting       ¨    0.5     NaN
g        6   Langiert       &    0.6      ^2
h        7   etcetera       *    0.7     NaN

In [ ]:

s10 = pd.Series([8, 'etc','(',.8,], index=['numbers','words','symbols','float'], name='i')
s11 = pd.Series([9, '...',')',.9,], index=['numbers','words','symbols','float'], name='j')
df5 = pd.DataFrame([s10, s11])
df1 = pd.concat([df1,df5])
df1

   numbers      words symbols  float signals
a        0  Eli Grant       !    0.0       +
b        1   triangle       @    0.1     NaN
c        2   integral       #    0.2     NaN
d        3   relating       $    0.3       -
e        4   altering       %    0.4     NaN
f        5   alerting       ¨    0.5     NaN
g        6   Langiert       &    0.6      ^2
h        7   etcetera       *    0.7     NaN
i        8        etc       (    0.8     NaN
j        9        ...       )    0.9     NaN

criando colunas a partir de colunas existentes

In [ ]:
df1['soma'] = df1['numbers'] + df1['float']
df1

   numbers      words symbols  float signals  soma
a        0  Eli Grant       !    0.0       +   0.0
b        1   triangle       @    0.1     NaN   1.1
c        2   integral       #    0.2     NaN   2.2
d        3   relating       $    0.3       -   3.3
e        4   altering       %    0.4     NaN   4.4
f        5   alerting       ¨    0.5     NaN   5.5
g        6   Langiert       &    0.6      ^2   6.6
h        7   etcetera       *    0.7     NaN   7.7
i        8        etc       (    0.8     NaN   8.8
j        9        ...       )    0.9     NaN   9.9

atribuindo um valor a uma coluna inteira

In [ ]:
df1['A'] = 9
df1.loc['e', 'A'] = 8
df1

   numbers      words symbols  float signals  soma  A
a        0  Eli Grant       !    0.0       +   0.0  9
b        1   triangle       @    0.1     NaN   1.1  9
c        2   integral       #    0.2     NaN   2.2  9
d        3   relating       $    0.3       -   3.3  9
e        4   altering       %    0.4     NaN   4.4  8
f        5   alerting       ¨    0.5     NaN   5.5  9
g        6   Langiert       &    0.6      ^2   6.6  9
h        7   etcetera       *    0.7     NaN   7.7  9
i        8        etc       (    0.8     NaN   8.8  9
j        9        ...       )    0.9     NaN   9.9  9

# Tratando NaN's (not a number)
NaN em um series ou um dataframe se refere a um valor vazio, sem nenhum preenchimento, e em pandas temos algumas formas de lidar com esses valores.

Retirando os comentarios abaixo pode-se testar um a um



*   fillna(value) -> todos os Nan serão substituidos pelo valor [value]
*   ffill() -> o valor vazio é preenchido com o valor antecessor a ele
*   bfill() -> o valor vazio é preenchido com o valor sucessor a ele
*   dropna() -> todas as linhas que conterem ao menos um valor vazio são deletadas

In [ ]:
#df1.fillna('/')
#df1.ffill()
#df1.bfill()
#df1.dropna()

   numbers      words symbols  float signals
a        0  Eli Grant       !    0.0       +
b        1   triangle       @    0.1       /
c        2   integral       #    0.2       /
d        3   relating       $    0.3       -
e        4   altering       %    0.4       /
f        5   alerting       ¨    0.5       /
g        6   Langiert       &    0.6      ^2
h        7   etcetera       *    0.7       /
i        8        etc       (    0.8       /
j        9        ...       )    0.9       /

# Inicializando informações

A celula a seguir contém uma base de dados com todos os pokemons  e algumas de suas informações até o nº 721. É uma célula bem extensa, recomenda-se apenas rodar ela, e a manter oculta

In [ ]:
nan = np.nan

pokemon = pd.DataFrame({'#': {0: 1, 1: 2, 2: 3, 3: 3, 4: 4, 5: 5, 6: 6, 7: 6, 8: 6, 9: 7, 10: 8, 11: 9, 12: 9, 13: 10, 14: 11, 15: 12, 16: 13, 17: 14, 18: 15, 19: 15, 20: 16, 21: 17, 22: 18, 23: 18, 24: 19, 25: 20, 26: 21, 27: 22, 28: 23, 29: 24, 30: 25, 31: 26, 32: 27, 33: 28, 34: 29, 35: 30, 36: 31, 37: 32, 38: 33, 39: 34, 40: 35, 41: 36, 42: 37, 43: 38, 44: 39, 45: 40, 46: 41, 47: 42, 48: 43, 49: 44, 50: 45, 51: 46, 52: 47, 53: 48, 54: 49, 55: 50, 56: 51, 57: 52, 58: 53, 59: 54, 60: 55, 61: 56, 62: 57, 63: 58, 64: 59, 65: 60, 66: 61, 67: 62, 68: 63, 69: 64, 70: 65, 71: 65, 72: 66, 73: 67, 74: 68, 75: 69, 76: 70, 77: 71, 78: 72, 79: 73, 80: 74, 81: 75, 82: 76, 83: 77, 84: 78, 85: 79, 86: 80, 87: 80, 88: 81, 89: 82, 90: 83, 91: 84, 92: 85, 93: 86, 94: 87, 95: 88, 96: 89, 97: 90, 98: 91, 99: 92, 100: 93, 101: 94, 102: 94, 103: 95, 104: 96, 105: 97, 106: 98, 107: 99, 108: 100, 109: 101, 110: 102, 111: 103, 112: 104, 113: 105, 114: 106, 115: 107, 116: 108, 117: 109, 118: 110, 119: 111, 120: 112, 121: 113, 122: 114, 123: 115, 124: 115, 125: 116, 126: 117, 127: 118, 128: 119, 129: 120, 130: 121, 131: 122, 132: 123, 133: 124, 134: 125, 135: 126, 136: 127, 137: 127, 138: 128, 139: 129, 140: 130, 141: 130, 142: 131, 143: 132, 144: 133, 145: 134, 146: 135, 147: 136, 148: 137, 149: 138, 150: 139, 151: 140, 152: 141, 153: 142, 154: 142, 155: 143, 156: 144, 157: 145, 158: 146, 159: 147, 160: 148, 161: 149, 162: 150, 163: 150, 164: 150, 165: 151, 166: 152, 167: 153, 168: 154, 169: 155, 170: 156, 171: 157, 172: 158, 173: 159, 174: 160, 175: 161, 176: 162, 177: 163, 178: 164, 179: 165, 180: 166, 181: 167, 182: 168, 183: 169, 184: 170, 185: 171, 186: 172, 187: 173, 188: 174, 189: 175, 190: 176, 191: 177, 192: 178, 193: 179, 194: 180, 195: 181, 196: 181, 197: 182, 198: 183, 199: 184, 200: 185, 201: 186, 202: 187, 203: 188, 204: 189, 205: 190, 206: 191, 207: 192, 208: 193, 209: 194, 210: 195, 211: 196, 212: 197, 213: 198, 214: 199, 215: 200, 216: 201, 217: 202, 218: 203, 219: 204, 220: 205, 221: 206, 222: 207, 223: 208, 224: 208, 225: 209, 226: 210, 227: 211, 228: 212, 229: 212, 230: 213, 231: 214, 232: 214, 233: 215, 234: 216, 235: 217, 236: 218, 237: 219, 238: 220, 239: 221, 240: 222, 241: 223, 242: 224, 243: 225, 244: 226, 245: 227, 246: 228, 247: 229, 248: 229, 249: 230, 250: 231, 251: 232, 252: 233, 253: 234, 254: 235, 255: 236, 256: 237, 257: 238, 258: 239, 259: 240, 260: 241, 261: 242, 262: 243, 263: 244, 264: 245, 265: 246, 266: 247, 267: 248, 268: 248, 269: 249, 270: 250, 271: 251, 272: 252, 273: 253, 274: 254, 275: 254, 276: 255, 277: 256, 278: 257, 279: 257, 280: 258, 281: 259, 282: 260, 283: 260, 284: 261, 285: 262, 286: 263, 287: 264, 288: 265, 289: 266, 290: 267, 291: 268, 292: 269, 293: 270, 294: 271, 295: 272, 296: 273, 297: 274, 298: 275, 299: 276, 300: 277, 301: 278, 302: 279, 303: 280, 304: 281, 305: 282, 306: 282, 307: 283, 308: 284, 309: 285, 310: 286, 311: 287, 312: 288, 313: 289, 314: 290, 315: 291, 316: 292, 317: 293, 318: 294, 319: 295, 320: 296, 321: 297, 322: 298, 323: 299, 324: 300, 325: 301, 326: 302, 327: 302, 328: 303, 329: 303, 330: 304, 331: 305, 332: 306, 333: 306, 334: 307, 335: 308, 336: 308, 337: 309, 338: 310, 339: 310, 340: 311, 341: 312, 342: 313, 343: 314, 344: 315, 345: 316, 346: 317, 347: 318, 348: 319, 349: 319, 350: 320, 351: 321, 352: 322, 353: 323, 354: 323, 355: 324, 356: 325, 357: 326, 358: 327, 359: 328, 360: 329, 361: 330, 362: 331, 363: 332, 364: 333, 365: 334, 366: 334, 367: 335, 368: 336, 369: 337, 370: 338, 371: 339, 372: 340, 373: 341, 374: 342, 375: 343, 376: 344, 377: 345, 378: 346, 379: 347, 380: 348, 381: 349, 382: 350, 383: 351, 384: 352, 385: 353, 386: 354, 387: 354, 388: 355, 389: 356, 390: 357, 391: 358, 392: 359, 393: 359, 394: 360, 395: 361, 396: 362, 397: 362, 398: 363, 399: 364, 400: 365, 401: 366, 402: 367, 403: 368, 404: 369, 405: 370, 406: 371, 407: 372, 408: 373, 409: 373, 410: 374, 411: 375, 412: 376, 413: 376, 414: 377, 415: 378, 416: 379, 417: 380, 418: 380, 419: 381, 420: 381, 421: 382, 422: 382, 423: 383, 424: 383, 425: 384, 426: 384, 427: 385, 428: 386, 429: 386, 430: 386, 431: 386, 432: 387, 433: 388, 434: 389, 435: 390, 436: 391, 437: 392, 438: 393, 439: 394, 440: 395, 441: 396, 442: 397, 443: 398, 444: 399, 445: 400, 446: 401, 447: 402, 448: 403, 449: 404, 450: 405, 451: 406, 452: 407, 453: 408, 454: 409, 455: 410, 456: 411, 457: 412, 458: 413, 459: 413, 460: 413, 461: 414, 462: 415, 463: 416, 464: 417, 465: 418, 466: 419, 467: 420, 468: 421, 469: 422, 470: 423, 471: 424, 472: 425, 473: 426, 474: 427, 475: 428, 476: 428, 477: 429, 478: 430, 479: 431, 480: 432, 481: 433, 482: 434, 483: 435, 484: 436, 485: 437, 486: 438, 487: 439, 488: 440, 489: 441, 490: 442, 491: 443, 492: 444, 493: 445, 494: 445, 495: 446, 496: 447, 497: 448, 498: 448, 499: 449, 500: 450, 501: 451, 502: 452, 503: 453, 504: 454, 505: 455, 506: 456, 507: 457, 508: 458, 509: 459, 510: 460, 511: 460, 512: 461, 513: 462, 514: 463, 515: 464, 516: 465, 517: 466, 518: 467, 519: 468, 520: 469, 521: 470, 522: 471, 523: 472, 524: 473, 525: 474, 526: 475, 527: 475, 528: 476, 529: 477, 530: 478, 531: 479, 532: 479, 533: 479, 534: 479, 535: 479, 536: 479, 537: 480, 538: 481, 539: 482, 540: 483, 541: 484, 542: 485, 543: 486, 544: 487, 545: 487, 546: 488, 547: 489, 548: 490, 549: 491, 550: 492, 551: 492, 552: 493, 553: 494, 554: 495, 555: 496, 556: 497, 557: 498, 558: 499, 559: 500, 560: 501, 561: 502, 562: 503, 563: 504, 564: 505, 565: 506, 566: 507, 567: 508, 568: 509, 569: 510, 570: 511, 571: 512, 572: 513, 573: 514, 574: 515, 575: 516, 576: 517, 577: 518, 578: 519, 579: 520, 580: 521, 581: 522, 582: 523, 583: 524, 584: 525, 585: 526, 586: 527, 587: 528, 588: 529, 589: 530, 590: 531, 591: 531, 592: 532, 593: 533, 594: 534, 595: 535, 596: 536, 597: 537, 598: 538, 599: 539, 600: 540, 601: 541, 602: 542, 603: 543, 604: 544, 605: 545, 606: 546, 607: 547, 608: 548, 609: 549, 610: 550, 611: 551, 612: 552, 613: 553, 614: 554, 615: 555, 616: 555, 617: 556, 618: 557, 619: 558, 620: 559, 621: 560, 622: 561, 623: 562, 624: 563, 625: 564, 626: 565, 627: 566, 628: 567, 629: 568, 630: 569, 631: 570, 632: 571, 633: 572, 634: 573, 635: 574, 636: 575, 637: 576, 638: 577, 639: 578, 640: 579, 641: 580, 642: 581, 643: 582, 644: 583, 645: 584, 646: 585, 647: 586, 648: 587, 649: 588, 650: 589, 651: 590, 652: 591, 653: 592, 654: 593, 655: 594, 656: 595, 657: 596, 658: 597, 659: 598, 660: 599, 661: 600, 662: 601, 663: 602, 664: 603, 665: 604, 666: 605, 667: 606, 668: 607, 669: 608, 670: 609, 671: 610, 672: 611, 673: 612, 674: 613, 675: 614, 676: 615, 677: 616, 678: 617, 679: 618, 680: 619, 681: 620, 682: 621, 683: 622, 684: 623, 685: 624, 686: 625, 687: 626, 688: 627, 689: 628, 690: 629, 691: 630, 692: 631, 693: 632, 694: 633, 695: 634, 696: 635, 697: 636, 698: 637, 699: 638, 700: 639, 701: 640, 702: 641, 703: 641, 704: 642, 705: 642, 706: 643, 707: 644, 708: 645, 709: 645, 710: 646, 711: 646, 712: 646, 713: 647, 714: 647, 715: 648, 716: 648, 717: 649, 718: 650, 719: 651, 720: 652, 721: 653, 722: 654, 723: 655, 724: 656, 725: 657, 726: 658, 727: 659, 728: 660, 729: 661, 730: 662, 731: 663, 732: 664, 733: 665, 734: 666, 735: 667, 736: 668, 737: 669, 738: 670, 739: 671, 740: 672, 741: 673, 742: 674, 743: 675, 744: 676, 745: 677, 746: 678, 747: 678, 748: 679, 749: 680, 750: 681, 751: 681, 752: 682, 753: 683, 754: 684, 755: 685, 756: 686, 757: 687, 758: 688, 759: 689, 760: 690, 761: 691, 762: 692, 763: 693, 764: 694, 765: 695, 766: 696, 767: 697, 768: 698, 769: 699, 770: 700, 771: 701, 772: 702, 773: 703, 774: 704, 775: 705, 776: 706, 777: 707, 778: 708, 779: 709, 780: 710, 781: 710, 782: 710, 783: 710, 784: 711, 785: 711, 786: 711, 787: 711, 788: 712, 789: 713, 790: 714, 791: 715, 792: 716, 793: 717, 794: 718, 795: 719, 796: 719, 797: 720, 798: 720, 799: 721}, 'Name': {0: 'Bulbasaur', 1: 'Ivysaur', 2: 'Venusaur', 3: 'VenusaurMega Venusaur', 4: 'Charmander', 5: 'Charmeleon', 6: 'Charizard', 7: 'CharizardMega Charizard X', 8: 'CharizardMega Charizard Y', 9: 'Squirtle', 10: 'Wartortle', 11: 'Blastoise', 12: 'BlastoiseMega Blastoise', 13: 'Caterpie', 14: 'Metapod', 15: 'Butterfree', 16: 'Weedle', 17: 'Kakuna', 18: 'Beedrill', 19: 'BeedrillMega Beedrill', 20: 'Pidgey', 21: 'Pidgeotto', 22: 'Pidgeot', 23: 'PidgeotMega Pidgeot', 24: 'Rattata', 25: 'Raticate', 26: 'Spearow', 27: 'Fearow', 28: 'Ekans', 29: 'Arbok', 30: 'Pikachu', 31: 'Raichu', 32: 'Sandshrew', 33: 'Sandslash', 34: 'Nidoran♀', 35: 'Nidorina', 36: 'Nidoqueen', 37: 'Nidoran♂', 38: 'Nidorino', 39: 'Nidoking', 40: 'Clefairy', 41: 'Clefable', 42: 'Vulpix', 43: 'Ninetales', 44: 'Jigglypuff', 45: 'Wigglytuff', 46: 'Zubat', 47: 'Golbat', 48: 'Oddish', 49: 'Gloom', 50: 'Vileplume', 51: 'Paras', 52: 'Parasect', 53: 'Venonat', 54: 'Venomoth', 55: 'Diglett', 56: 'Dugtrio', 57: 'Meowth', 58: 'Persian', 59: 'Psyduck', 60: 'Golduck', 61: 'Mankey', 62: 'Primeape', 63: 'Growlithe', 64: 'Arcanine', 65: 'Poliwag', 66: 'Poliwhirl', 67: 'Poliwrath', 68: 'Abra', 69: 'Kadabra', 70: 'Alakazam', 71: 'AlakazamMega Alakazam', 72: 'Machop', 73: 'Machoke', 74: 'Machamp', 75: 'Bellsprout', 76: 'Weepinbell', 77: 'Victreebel', 78: 'Tentacool', 79: 'Tentacruel', 80: 'Geodude', 81: 'Graveler', 82: 'Golem', 83: 'Ponyta', 84: 'Rapidash', 85: 'Slowpoke', 86: 'Slowbro', 87: 'SlowbroMega Slowbro', 88: 'Magnemite', 89: 'Magneton', 90: "Farfetch'd", 91: 'Doduo', 92: 'Dodrio', 93: 'Seel', 94: 'Dewgong', 95: 'Grimer', 96: 'Muk', 97: 'Shellder', 98: 'Cloyster', 99: 'Gastly', 100: 'Haunter', 101: 'Gengar', 102: 'GengarMega Gengar', 103: 'Onix', 104: 'Drowzee', 105: 'Hypno', 106: 'Krabby', 107: 'Kingler', 108: 'Voltorb', 109: 'Electrode', 110: 'Exeggcute', 111: 'Exeggutor', 112: 'Cubone', 113: 'Marowak', 114: 'Hitmonlee', 115: 'Hitmonchan', 116: 'Lickitung', 117: 'Koffing', 118: 'Weezing', 119: 'Rhyhorn', 120: 'Rhydon', 121: 'Chansey', 122: 'Tangela', 123: 'Kangaskhan', 124: 'KangaskhanMega Kangaskhan', 125: 'Horsea', 126: 'Seadra', 127: 'Goldeen', 128: 'Seaking', 129: 'Staryu', 130: 'Starmie', 131: 'Mr. Mime', 132: 'Scyther', 133: 'Jynx', 134: 'Electabuzz', 135: 'Magmar', 136: 'Pinsir', 137: 'PinsirMega Pinsir', 138: 'Tauros', 139: 'Magikarp', 140: 'Gyarados', 141: 'GyaradosMega Gyarados', 142: 'Lapras', 143: 'Ditto', 144: 'Eevee', 145: 'Vaporeon', 146: 'Jolteon', 147: 'Flareon', 148: 'Porygon', 149: 'Omanyte', 150: 'Omastar', 151: 'Kabuto', 152: 'Kabutops', 153: 'Aerodactyl', 154: 'AerodactylMega Aerodactyl', 155: 'Snorlax', 156: 'Articuno', 157: 'Zapdos', 158: 'Moltres', 159: 'Dratini', 160: 'Dragonair', 161: 'Dragonite', 162: 'Mewtwo', 163: 'MewtwoMega Mewtwo X', 164: 'MewtwoMega Mewtwo Y', 165: 'Mew', 166: 'Chikorita', 167: 'Bayleef', 168: 'Meganium', 169: 'Cyndaquil', 170: 'Quilava', 171: 'Typhlosion', 172: 'Totodile', 173: 'Croconaw', 174: 'Feraligatr', 175: 'Sentret', 176: 'Furret', 177: 'Hoothoot', 178: 'Noctowl', 179: 'Ledyba', 180: 'Ledian', 181: 'Spinarak', 182: 'Ariados', 183: 'Crobat', 184: 'Chinchou', 185: 'Lanturn', 186: 'Pichu', 187: 'Cleffa', 188: 'Igglybuff', 189: 'Togepi', 190: 'Togetic', 191: 'Natu', 192: 'Xatu', 193: 'Mareep', 194: 'Flaaffy', 195: 'Ampharos', 196: 'AmpharosMega Ampharos', 197: 'Bellossom', 198: 'Marill', 199: 'Azumarill', 200: 'Sudowoodo', 201: 'Politoed', 202: 'Hoppip', 203: 'Skiploom', 204: 'Jumpluff', 205: 'Aipom', 206: 'Sunkern', 207: 'Sunflora', 208: 'Yanma', 209: 'Wooper', 210: 'Quagsire', 211: 'Espeon', 212: 'Umbreon', 213: 'Murkrow', 214: 'Slowking', 215: 'Misdreavus', 216: 'Unown', 217: 'Wobbuffet', 218: 'Girafarig', 219: 'Pineco', 220: 'Forretress', 221: 'Dunsparce', 222: 'Gligar', 223: 'Steelix', 224: 'SteelixMega Steelix', 225: 'Snubbull', 226: 'Granbull', 227: 'Qwilfish', 228: 'Scizor', 229: 'ScizorMega Scizor', 230: 'Shuckle', 231: 'Heracross', 232: 'HeracrossMega Heracross', 233: 'Sneasel', 234: 'Teddiursa', 235: 'Ursaring', 236: 'Slugma', 237: 'Magcargo', 238: 'Swinub', 239: 'Piloswine', 240: 'Corsola', 241: 'Remoraid', 242: 'Octillery', 243: 'Delibird', 244: 'Mantine', 245: 'Skarmory', 246: 'Houndour', 247: 'Houndoom', 248: 'HoundoomMega Houndoom', 249: 'Kingdra', 250: 'Phanpy', 251: 'Donphan', 252: 'Porygon2', 253: 'Stantler', 254: 'Smeargle', 255: 'Tyrogue', 256: 'Hitmontop', 257: 'Smoochum', 258: 'Elekid', 259: 'Magby', 260: 'Miltank', 261: 'Blissey', 262: 'Raikou', 263: 'Entei', 264: 'Suicune', 265: 'Larvitar', 266: 'Pupitar', 267: 'Tyranitar', 268: 'TyranitarMega Tyranitar', 269: 'Lugia', 270: 'Ho-oh', 271: 'Celebi', 272: 'Treecko', 273: 'Grovyle', 274: 'Sceptile', 275: 'SceptileMega Sceptile', 276: 'Torchic', 277: 'Combusken', 278: 'Blaziken', 279: 'BlazikenMega Blaziken', 280: 'Mudkip', 281: 'Marshtomp', 282: 'Swampert', 283: 'SwampertMega Swampert', 284: 'Poochyena', 285: 'Mightyena', 286: 'Zigzagoon', 287: 'Linoone', 288: 'Wurmple', 289: 'Silcoon', 290: 'Beautifly', 291: 'Cascoon', 292: 'Dustox', 293: 'Lotad', 294: 'Lombre', 295: 'Ludicolo', 296: 'Seedot', 297: 'Nuzleaf', 298: 'Shiftry', 299: 'Taillow', 300: 'Swellow', 301: 'Wingull', 302: 'Pelipper', 303: 'Ralts', 304: 'Kirlia', 305: 'Gardevoir', 306: 'GardevoirMega Gardevoir', 307: 'Surskit', 308: 'Masquerain', 309: 'Shroomish', 310: 'Breloom', 311: 'Slakoth', 312: 'Vigoroth', 313: 'Slaking', 314: 'Nincada', 315: 'Ninjask', 316: 'Shedinja', 317: 'Whismur', 318: 'Loudred', 319: 'Exploud', 320: 'Makuhita', 321: 'Hariyama', 322: 'Azurill', 323: 'Nosepass', 324: 'Skitty', 325: 'Delcatty', 326: 'Sableye', 327: 'SableyeMega Sableye', 328: 'Mawile', 329: 'MawileMega Mawile', 330: 'Aron', 331: 'Lairon', 332: 'Aggron', 333: 'AggronMega Aggron', 334: 'Meditite', 335: 'Medicham', 336: 'MedichamMega Medicham', 337: 'Electrike', 338: 'Manectric', 339: 'ManectricMega Manectric', 340: 'Plusle', 341: 'Minun', 342: 'Volbeat', 343: 'Illumise', 344: 'Roselia', 345: 'Gulpin', 346: 'Swalot', 347: 'Carvanha', 348: 'Sharpedo', 349: 'SharpedoMega Sharpedo', 350: 'Wailmer', 351: 'Wailord', 352: 'Numel', 353: 'Camerupt', 354: 'CameruptMega Camerupt', 355: 'Torkoal', 356: 'Spoink', 357: 'Grumpig', 358: 'Spinda', 359: 'Trapinch', 360: 'Vibrava', 361: 'Flygon', 362: 'Cacnea', 363: 'Cacturne', 364: 'Swablu', 365: 'Altaria', 366: 'AltariaMega Altaria', 367: 'Zangoose', 368: 'Seviper', 369: 'Lunatone', 370: 'Solrock', 371: 'Barboach', 372: 'Whiscash', 373: 'Corphish', 374: 'Crawdaunt', 375: 'Baltoy', 376: 'Claydol', 377: 'Lileep', 378: 'Cradily', 379: 'Anorith', 380: 'Armaldo', 381: 'Feebas', 382: 'Milotic', 383: 'Castform', 384: 'Kecleon', 385: 'Shuppet', 386: 'Banette', 387: 'BanetteMega Banette', 388: 'Duskull', 389: 'Dusclops', 390: 'Tropius', 391: 'Chimecho', 392: 'Absol', 393: 'AbsolMega Absol', 394: 'Wynaut', 395: 'Snorunt', 396: 'Glalie', 397: 'GlalieMega Glalie', 398: 'Spheal', 399: 'Sealeo', 400: 'Walrein', 401: 'Clamperl', 402: 'Huntail', 403: 'Gorebyss', 404: 'Relicanth', 405: 'Luvdisc', 406: 'Bagon', 407: 'Shelgon', 408: 'Salamence', 409: 'SalamenceMega Salamence', 410: 'Beldum', 411: 'Metang', 412: 'Metagross', 413: 'MetagrossMega Metagross', 414: 'Regirock', 415: 'Regice', 416: 'Registeel', 417: 'Latias', 418: 'LatiasMega Latias', 419: 'Latios', 420: 'LatiosMega Latios', 421: 'Kyogre', 422: 'KyogrePrimal Kyogre', 423: 'Groudon', 424: 'GroudonPrimal Groudon', 425: 'Rayquaza', 426: 'RayquazaMega Rayquaza', 427: 'Jirachi', 428: 'DeoxysNormal Forme', 429: 'DeoxysAttack Forme', 430: 'DeoxysDefense Forme', 431: 'DeoxysSpeed Forme', 432: 'Turtwig', 433: 'Grotle', 434: 'Torterra', 435: 'Chimchar', 436: 'Monferno', 437: 'Infernape', 438: 'Piplup', 439: 'Prinplup', 440: 'Empoleon', 441: 'Starly', 442: 'Staravia', 443: 'Staraptor', 444: 'Bidoof', 445: 'Bibarel', 446: 'Kricketot', 447: 'Kricketune', 448: 'Shinx', 449: 'Luxio', 450: 'Luxray', 451: 'Budew', 452: 'Roserade', 453: 'Cranidos', 454: 'Rampardos', 455: 'Shieldon', 456: 'Bastiodon', 457: 'Burmy', 458: 'WormadamPlant Cloak', 459: 'WormadamSandy Cloak', 460: 'WormadamTrash Cloak', 461: 'Mothim', 462: 'Combee', 463: 'Vespiquen', 464: 'Pachirisu', 465: 'Buizel', 466: 'Floatzel', 467: 'Cherubi', 468: 'Cherrim', 469: 'Shellos', 470: 'Gastrodon', 471: 'Ambipom', 472: 'Drifloon', 473: 'Drifblim', 474: 'Buneary', 475: 'Lopunny', 476: 'LopunnyMega Lopunny', 477: 'Mismagius', 478: 'Honchkrow', 479: 'Glameow', 480: 'Purugly', 481: 'Chingling', 482: 'Stunky', 483: 'Skuntank', 484: 'Bronzor', 485: 'Bronzong', 486: 'Bonsly', 487: 'Mime Jr.', 488: 'Happiny', 489: 'Chatot', 490: 'Spiritomb', 491: 'Gible', 492: 'Gabite', 493: 'Garchomp', 494: 'GarchompMega Garchomp', 495: 'Munchlax', 496: 'Riolu', 497: 'Lucario', 498: 'LucarioMega Lucario', 499: 'Hippopotas', 500: 'Hippowdon', 501: 'Skorupi', 502: 'Drapion', 503: 'Croagunk', 504: 'Toxicroak', 505: 'Carnivine', 506: 'Finneon', 507: 'Lumineon', 508: 'Mantyke', 509: 'Snover', 510: 'Abomasnow', 511: 'AbomasnowMega Abomasnow', 512: 'Weavile', 513: 'Magnezone', 514: 'Lickilicky', 515: 'Rhyperior', 516: 'Tangrowth', 517: 'Electivire', 518: 'Magmortar', 519: 'Togekiss', 520: 'Yanmega', 521: 'Leafeon', 522: 'Glaceon', 523: 'Gliscor', 524: 'Mamoswine', 525: 'Porygon-Z', 526: 'Gallade', 527: 'GalladeMega Gallade', 528: 'Probopass', 529: 'Dusknoir', 530: 'Froslass', 531: 'Rotom', 532: 'RotomHeat Rotom', 533: 'RotomWash Rotom', 534: 'RotomFrost Rotom', 535: 'RotomFan Rotom', 536: 'RotomMow Rotom', 537: 'Uxie', 538: 'Mesprit', 539: 'Azelf', 540: 'Dialga', 541: 'Palkia', 542: 'Heatran', 543: 'Regigigas', 544: 'GiratinaAltered Forme', 545: 'GiratinaOrigin Forme', 546: 'Cresselia', 547: 'Phione', 548: 'Manaphy', 549: 'Darkrai', 550: 'ShayminLand Forme', 551: 'ShayminSky Forme', 552: 'Arceus', 553: 'Victini', 554: 'Snivy', 555: 'Servine', 556: 'Serperior', 557: 'Tepig', 558: 'Pignite', 559: 'Emboar', 560: 'Oshawott', 561: 'Dewott', 562: 'Samurott', 563: 'Patrat', 564: 'Watchog', 565: 'Lillipup', 566: 'Herdier', 567: 'Stoutland', 568: 'Purrloin', 569: 'Liepard', 570: 'Pansage', 571: 'Simisage', 572: 'Pansear', 573: 'Simisear', 574: 'Panpour', 575: 'Simipour', 576: 'Munna', 577: 'Musharna', 578: 'Pidove', 579: 'Tranquill', 580: 'Unfezant', 581: 'Blitzle', 582: 'Zebstrika', 583: 'Roggenrola', 584: 'Boldore', 585: 'Gigalith', 586: 'Woobat', 587: 'Swoobat', 588: 'Drilbur', 589: 'Excadrill', 590: 'Audino', 591: 'AudinoMega Audino', 592: 'Timburr', 593: 'Gurdurr', 594: 'Conkeldurr', 595: 'Tympole', 596: 'Palpitoad', 597: 'Seismitoad', 598: 'Throh', 599: 'Sawk', 600: 'Sewaddle', 601: 'Swadloon', 602: 'Leavanny', 603: 'Venipede', 604: 'Whirlipede', 605: 'Scolipede', 606: 'Cottonee', 607: 'Whimsicott', 608: 'Petilil', 609: 'Lilligant', 610: 'Basculin', 611: 'Sandile', 612: 'Krokorok', 613: 'Krookodile', 614: 'Darumaka', 615: 'DarmanitanStandard Mode', 616: 'DarmanitanZen Mode', 617: 'Maractus', 618: 'Dwebble', 619: 'Crustle', 620: 'Scraggy', 621: 'Scrafty', 622: 'Sigilyph', 623: 'Yamask', 624: 'Cofagrigus', 625: 'Tirtouga', 626: 'Carracosta', 627: 'Archen', 628: 'Archeops', 629: 'Trubbish', 630: 'Garbodor', 631: 'Zorua', 632: 'Zoroark', 633: 'Minccino', 634: 'Cinccino', 635: 'Gothita', 636: 'Gothorita', 637: 'Gothitelle', 638: 'Solosis', 639: 'Duosion', 640: 'Reuniclus', 641: 'Ducklett', 642: 'Swanna', 643: 'Vanillite', 644: 'Vanillish', 645: 'Vanilluxe', 646: 'Deerling', 647: 'Sawsbuck', 648: 'Emolga', 649: 'Karrablast', 650: 'Escavalier', 651: 'Foongus', 652: 'Amoonguss', 653: 'Frillish', 654: 'Jellicent', 655: 'Alomomola', 656: 'Joltik', 657: 'Galvantula', 658: 'Ferroseed', 659: 'Ferrothorn', 660: 'Klink', 661: 'Klang', 662: 'Klinklang', 663: 'Tynamo', 664: 'Eelektrik', 665: 'Eelektross', 666: 'Elgyem', 667: 'Beheeyem', 668: 'Litwick', 669: 'Lampent', 670: 'Chandelure', 671: 'Axew', 672: 'Fraxure', 673: 'Haxorus', 674: 'Cubchoo', 675: 'Beartic', 676: 'Cryogonal', 677: 'Shelmet', 678: 'Accelgor', 679: 'Stunfisk', 680: 'Mienfoo', 681: 'Mienshao', 682: 'Druddigon', 683: 'Golett', 684: 'Golurk', 685: 'Pawniard', 686: 'Bisharp', 687: 'Bouffalant', 688: 'Rufflet', 689: 'Braviary', 690: 'Vullaby', 691: 'Mandibuzz', 692: 'Heatmor', 693: 'Durant', 694: 'Deino', 695: 'Zweilous', 696: 'Hydreigon', 697: 'Larvesta', 698: 'Volcarona', 699: 'Cobalion', 700: 'Terrakion', 701: 'Virizion', 702: 'TornadusIncarnate Forme', 703: 'TornadusTherian Forme', 704: 'ThundurusIncarnate Forme', 705: 'ThundurusTherian Forme', 706: 'Reshiram', 707: 'Zekrom', 708: 'LandorusIncarnate Forme', 709: 'LandorusTherian Forme', 710: 'Kyurem', 711: 'KyuremBlack Kyurem', 712: 'KyuremWhite Kyurem', 713: 'KeldeoOrdinary Forme', 714: 'KeldeoResolute Forme', 715: 'MeloettaAria Forme', 716: 'MeloettaPirouette Forme', 717: 'Genesect', 718: 'Chespin', 719: 'Quilladin', 720: 'Chesnaught', 721: 'Fennekin', 722: 'Braixen', 723: 'Delphox', 724: 'Froakie', 725: 'Frogadier', 726: 'Greninja', 727: 'Bunnelby', 728: 'Diggersby', 729: 'Fletchling', 730: 'Fletchinder', 731: 'Talonflame', 732: 'Scatterbug', 733: 'Spewpa', 734: 'Vivillon', 735: 'Litleo', 736: 'Pyroar', 737: 'Flabébé', 738: 'Floette', 739: 'Florges', 740: 'Skiddo', 741: 'Gogoat', 742: 'Pancham', 743: 'Pangoro', 744: 'Furfrou', 745: 'Espurr', 746: 'MeowsticMale', 747: 'MeowsticFemale', 748: 'Honedge', 749: 'Doublade', 750: 'AegislashBlade Forme', 751: 'AegislashShield Forme', 752: 'Spritzee', 753: 'Aromatisse', 754: 'Swirlix', 755: 'Slurpuff', 756: 'Inkay', 757: 'Malamar', 758: 'Binacle', 759: 'Barbaracle', 760: 'Skrelp', 761: 'Dragalge', 762: 'Clauncher', 763: 'Clawitzer', 764: 'Helioptile', 765: 'Heliolisk', 766: 'Tyrunt', 767: 'Tyrantrum', 768: 'Amaura', 769: 'Aurorus', 770: 'Sylveon', 771: 'Hawlucha', 772: 'Dedenne', 773: 'Carbink', 774: 'Goomy', 775: 'Sliggoo', 776: 'Goodra', 777: 'Klefki', 778: 'Phantump', 779: 'Trevenant', 780: 'PumpkabooAverage Size', 781: 'PumpkabooSmall Size', 782: 'PumpkabooLarge Size', 783: 'PumpkabooSuper Size', 784: 'GourgeistAverage Size', 785: 'GourgeistSmall Size', 786: 'GourgeistLarge Size', 787: 'GourgeistSuper Size', 788: 'Bergmite', 789: 'Avalugg', 790: 'Noibat', 791: 'Noivern', 792: 'Xerneas', 793: 'Yveltal', 794: 'Zygarde50% Forme', 795: 'Diancie', 796: 'DiancieMega Diancie', 797: 'HoopaHoopa Confined', 798: 'HoopaHoopa Unbound', 799: 'Volcanion'}, 'Type 1': {0: 'Grass', 1: 'Grass', 2: 'Grass', 3: 'Grass', 4: 'Fire', 5: 'Fire', 6: 'Fire', 7: 'Fire', 8: 'Fire', 9: 'Water', 10: 'Water', 11: 'Water', 12: 'Water', 13: 'Bug', 14: 'Bug', 15: 'Bug', 16: 'Bug', 17: 'Bug', 18: 'Bug', 19: 'Bug', 20: 'Normal', 21: 'Normal', 22: 'Normal', 23: 'Normal', 24: 'Normal', 25: 'Normal', 26: 'Normal', 27: 'Normal', 28: 'Poison', 29: 'Poison', 30: 'Electric', 31: 'Electric', 32: 'Ground', 33: 'Ground', 34: 'Poison', 35: 'Poison', 36: 'Poison', 37: 'Poison', 38: 'Poison', 39: 'Poison', 40: 'Fairy', 41: 'Fairy', 42: 'Fire', 43: 'Fire', 44: 'Normal', 45: 'Normal', 46: 'Poison', 47: 'Poison', 48: 'Grass', 49: 'Grass', 50: 'Grass', 51: 'Bug', 52: 'Bug', 53: 'Bug', 54: 'Bug', 55: 'Ground', 56: 'Ground', 57: 'Normal', 58: 'Normal', 59: 'Water', 60: 'Water', 61: 'Fighting', 62: 'Fighting', 63: 'Fire', 64: 'Fire', 65: 'Water', 66: 'Water', 67: 'Water', 68: 'Psychic', 69: 'Psychic', 70: 'Psychic', 71: 'Psychic', 72: 'Fighting', 73: 'Fighting', 74: 'Fighting', 75: 'Grass', 76: 'Grass', 77: 'Grass', 78: 'Water', 79: 'Water', 80: 'Rock', 81: 'Rock', 82: 'Rock', 83: 'Fire', 84: 'Fire', 85: 'Water', 86: 'Water', 87: 'Water', 88: 'Electric', 89: 'Electric', 90: 'Normal', 91: 'Normal', 92: 'Normal', 93: 'Water', 94: 'Water', 95: 'Poison', 96: 'Poison', 97: 'Water', 98: 'Water', 99: 'Ghost', 100: 'Ghost', 101: 'Ghost', 102: 'Ghost', 103: 'Rock', 104: 'Psychic', 105: 'Psychic', 106: 'Water', 107: 'Water', 108: 'Electric', 109: 'Electric', 110: 'Grass', 111: 'Grass', 112: 'Ground', 113: 'Ground', 114: 'Fighting', 115: 'Fighting', 116: 'Normal', 117: 'Poison', 118: 'Poison', 119: 'Ground', 120: 'Ground', 121: 'Normal', 122: 'Grass', 123: 'Normal', 124: 'Normal', 125: 'Water', 126: 'Water', 127: 'Water', 128: 'Water', 129: 'Water', 130: 'Water', 131: 'Psychic', 132: 'Bug', 133: 'Ice', 134: 'Electric', 135: 'Fire', 136: 'Bug', 137: 'Bug', 138: 'Normal', 139: 'Water', 140: 'Water', 141: 'Water', 142: 'Water', 143: 'Normal', 144: 'Normal', 145: 'Water', 146: 'Electric', 147: 'Fire', 148: 'Normal', 149: 'Rock', 150: 'Rock', 151: 'Rock', 152: 'Rock', 153: 'Rock', 154: 'Rock', 155: 'Normal', 156: 'Ice', 157: 'Electric', 158: 'Fire', 159: 'Dragon', 160: 'Dragon', 161: 'Dragon', 162: 'Psychic', 163: 'Psychic', 164: 'Psychic', 165: 'Psychic', 166: 'Grass', 167: 'Grass', 168: 'Grass', 169: 'Fire', 170: 'Fire', 171: 'Fire', 172: 'Water', 173: 'Water', 174: 'Water', 175: 'Normal', 176: 'Normal', 177: 'Normal', 178: 'Normal', 179: 'Bug', 180: 'Bug', 181: 'Bug', 182: 'Bug', 183: 'Poison', 184: 'Water', 185: 'Water', 186: 'Electric', 187: 'Fairy', 188: 'Normal', 189: 'Fairy', 190: 'Fairy', 191: 'Psychic', 192: 'Psychic', 193: 'Electric', 194: 'Electric', 195: 'Electric', 196: 'Electric', 197: 'Grass', 198: 'Water', 199: 'Water', 200: 'Rock', 201: 'Water', 202: 'Grass', 203: 'Grass', 204: 'Grass', 205: 'Normal', 206: 'Grass', 207: 'Grass', 208: 'Bug', 209: 'Water', 210: 'Water', 211: 'Psychic', 212: 'Dark', 213: 'Dark', 214: 'Water', 215: 'Ghost', 216: 'Psychic', 217: 'Psychic', 218: 'Normal', 219: 'Bug', 220: 'Bug', 221: 'Normal', 222: 'Ground', 223: 'Steel', 224: 'Steel', 225: 'Fairy', 226: 'Fairy', 227: 'Water', 228: 'Bug', 229: 'Bug', 230: 'Bug', 231: 'Bug', 232: 'Bug', 233: 'Dark', 234: 'Normal', 235: 'Normal', 236: 'Fire', 237: 'Fire', 238: 'Ice', 239: 'Ice', 240: 'Water', 241: 'Water', 242: 'Water', 243: 'Ice', 244: 'Water', 245: 'Steel', 246: 'Dark', 247: 'Dark', 248: 'Dark', 249: 'Water', 250: 'Ground', 251: 'Ground', 252: 'Normal', 253: 'Normal', 254: 'Normal', 255: 'Fighting', 256: 'Fighting', 257: 'Ice', 258: 'Electric', 259: 'Fire', 260: 'Normal', 261: 'Normal', 262: 'Electric', 263: 'Fire', 264: 'Water', 265: 'Rock', 266: 'Rock', 267: 'Rock', 268: 'Rock', 269: 'Psychic', 270: 'Fire', 271: 'Psychic', 272: 'Grass', 273: 'Grass', 274: 'Grass', 275: 'Grass', 276: 'Fire', 277: 'Fire', 278: 'Fire', 279: 'Fire', 280: 'Water', 281: 'Water', 282: 'Water', 283: 'Water', 284: 'Dark', 285: 'Dark', 286: 'Normal', 287: 'Normal', 288: 'Bug', 289: 'Bug', 290: 'Bug', 291: 'Bug', 292: 'Bug', 293: 'Water', 294: 'Water', 295: 'Water', 296: 'Grass', 297: 'Grass', 298: 'Grass', 299: 'Normal', 300: 'Normal', 301: 'Water', 302: 'Water', 303: 'Psychic', 304: 'Psychic', 305: 'Psychic', 306: 'Psychic', 307: 'Bug', 308: 'Bug', 309: 'Grass', 310: 'Grass', 311: 'Normal', 312: 'Normal', 313: 'Normal', 314: 'Bug', 315: 'Bug', 316: 'Bug', 317: 'Normal', 318: 'Normal', 319: 'Normal', 320: 'Fighting', 321: 'Fighting', 322: 'Normal', 323: 'Rock', 324: 'Normal', 325: 'Normal', 326: 'Dark', 327: 'Dark', 328: 'Steel', 329: 'Steel', 330: 'Steel', 331: 'Steel', 332: 'Steel', 333: 'Steel', 334: 'Fighting', 335: 'Fighting', 336: 'Fighting', 337: 'Electric', 338: 'Electric', 339: 'Electric', 340: 'Electric', 341: 'Electric', 342: 'Bug', 343: 'Bug', 344: 'Grass', 345: 'Poison', 346: 'Poison', 347: 'Water', 348: 'Water', 349: 'Water', 350: 'Water', 351: 'Water', 352: 'Fire', 353: 'Fire', 354: 'Fire', 355: 'Fire', 356: 'Psychic', 357: 'Psychic', 358: 'Normal', 359: 'Ground', 360: 'Ground', 361: 'Ground', 362: 'Grass', 363: 'Grass', 364: 'Normal', 365: 'Dragon', 366: 'Dragon', 367: 'Normal', 368: 'Poison', 369: 'Rock', 370: 'Rock', 371: 'Water', 372: 'Water', 373: 'Water', 374: 'Water', 375: 'Ground', 376: 'Ground', 377: 'Rock', 378: 'Rock', 379: 'Rock', 380: 'Rock', 381: 'Water', 382: 'Water', 383: 'Normal', 384: 'Normal', 385: 'Ghost', 386: 'Ghost', 387: 'Ghost', 388: 'Ghost', 389: 'Ghost', 390: 'Grass', 391: 'Psychic', 392: 'Dark', 393: 'Dark', 394: 'Psychic', 395: 'Ice', 396: 'Ice', 397: 'Ice', 398: 'Ice', 399: 'Ice', 400: 'Ice', 401: 'Water', 402: 'Water', 403: 'Water', 404: 'Water', 405: 'Water', 406: 'Dragon', 407: 'Dragon', 408: 'Dragon', 409: 'Dragon', 410: 'Steel', 411: 'Steel', 412: 'Steel', 413: 'Steel', 414: 'Rock', 415: 'Ice', 416: 'Steel', 417: 'Dragon', 418: 'Dragon', 419: 'Dragon', 420: 'Dragon', 421: 'Water', 422: 'Water', 423: 'Ground', 424: 'Ground', 425: 'Dragon', 426: 'Dragon', 427: 'Steel', 428: 'Psychic', 429: 'Psychic', 430: 'Psychic', 431: 'Psychic', 432: 'Grass', 433: 'Grass', 434: 'Grass', 435: 'Fire', 436: 'Fire', 437: 'Fire', 438: 'Water', 439: 'Water', 440: 'Water', 441: 'Normal', 442: 'Normal', 443: 'Normal', 444: 'Normal', 445: 'Normal', 446: 'Bug', 447: 'Bug', 448: 'Electric', 449: 'Electric', 450: 'Electric', 451: 'Grass', 452: 'Grass', 453: 'Rock', 454: 'Rock', 455: 'Rock', 456: 'Rock', 457: 'Bug', 458: 'Bug', 459: 'Bug', 460: 'Bug', 461: 'Bug', 462: 'Bug', 463: 'Bug', 464: 'Electric', 465: 'Water', 466: 'Water', 467: 'Grass', 468: 'Grass', 469: 'Water', 470: 'Water', 471: 'Normal', 472: 'Ghost', 473: 'Ghost', 474: 'Normal', 475: 'Normal', 476: 'Normal', 477: 'Ghost', 478: 'Dark', 479: 'Normal', 480: 'Normal', 481: 'Psychic', 482: 'Poison', 483: 'Poison', 484: 'Steel', 485: 'Steel', 486: 'Rock', 487: 'Psychic', 488: 'Normal', 489: 'Normal', 490: 'Ghost', 491: 'Dragon', 492: 'Dragon', 493: 'Dragon', 494: 'Dragon', 495: 'Normal', 496: 'Fighting', 497: 'Fighting', 498: 'Fighting', 499: 'Ground', 500: 'Ground', 501: 'Poison', 502: 'Poison', 503: 'Poison', 504: 'Poison', 505: 'Grass', 506: 'Water', 507: 'Water', 508: 'Water', 509: 'Grass', 510: 'Grass', 511: 'Grass', 512: 'Dark', 513: 'Electric', 514: 'Normal', 515: 'Ground', 516: 'Grass', 517: 'Electric', 518: 'Fire', 519: 'Fairy', 520: 'Bug', 521: 'Grass', 522: 'Ice', 523: 'Ground', 524: 'Ice', 525: 'Normal', 526: 'Psychic', 527: 'Psychic', 528: 'Rock', 529: 'Ghost', 530: 'Ice', 531: 'Electric', 532: 'Electric', 533: 'Electric', 534: 'Electric', 535: 'Electric', 536: 'Electric', 537: 'Psychic', 538: 'Psychic', 539: 'Psychic', 540: 'Steel', 541: 'Water', 542: 'Fire', 543: 'Normal', 544: 'Ghost', 545: 'Ghost', 546: 'Psychic', 547: 'Water', 548: 'Water', 549: 'Dark', 550: 'Grass', 551: 'Grass', 552: 'Normal', 553: 'Psychic', 554: 'Grass', 555: 'Grass', 556: 'Grass', 557: 'Fire', 558: 'Fire', 559: 'Fire', 560: 'Water', 561: 'Water', 562: 'Water', 563: 'Normal', 564: 'Normal', 565: 'Normal', 566: 'Normal', 567: 'Normal', 568: 'Dark', 569: 'Dark', 570: 'Grass', 571: 'Grass', 572: 'Fire', 573: 'Fire', 574: 'Water', 575: 'Water', 576: 'Psychic', 577: 'Psychic', 578: 'Normal', 579: 'Normal', 580: 'Normal', 581: 'Electric', 582: 'Electric', 583: 'Rock', 584: 'Rock', 585: 'Rock', 586: 'Psychic', 587: 'Psychic', 588: 'Ground', 589: 'Ground', 590: 'Normal', 591: 'Normal', 592: 'Fighting', 593: 'Fighting', 594: 'Fighting', 595: 'Water', 596: 'Water', 597: 'Water', 598: 'Fighting', 599: 'Fighting', 600: 'Bug', 601: 'Bug', 602: 'Bug', 603: 'Bug', 604: 'Bug', 605: 'Bug', 606: 'Grass', 607: 'Grass', 608: 'Grass', 609: 'Grass', 610: 'Water', 611: 'Ground', 612: 'Ground', 613: 'Ground', 614: 'Fire', 615: 'Fire', 616: 'Fire', 617: 'Grass', 618: 'Bug', 619: 'Bug', 620: 'Dark', 621: 'Dark', 622: 'Psychic', 623: 'Ghost', 624: 'Ghost', 625: 'Water', 626: 'Water', 627: 'Rock', 628: 'Rock', 629: 'Poison', 630: 'Poison', 631: 'Dark', 632: 'Dark', 633: 'Normal', 634: 'Normal', 635: 'Psychic', 636: 'Psychic', 637: 'Psychic', 638: 'Psychic', 639: 'Psychic', 640: 'Psychic', 641: 'Water', 642: 'Water', 643: 'Ice', 644: 'Ice', 645: 'Ice', 646: 'Normal', 647: 'Normal', 648: 'Electric', 649: 'Bug', 650: 'Bug', 651: 'Grass', 652: 'Grass', 653: 'Water', 654: 'Water', 655: 'Water', 656: 'Bug', 657: 'Bug', 658: 'Grass', 659: 'Grass', 660: 'Steel', 661: 'Steel', 662: 'Steel', 663: 'Electric', 664: 'Electric', 665: 'Electric', 666: 'Psychic', 667: 'Psychic', 668: 'Ghost', 669: 'Ghost', 670: 'Ghost', 671: 'Dragon', 672: 'Dragon', 673: 'Dragon', 674: 'Ice', 675: 'Ice', 676: 'Ice', 677: 'Bug', 678: 'Bug', 679: 'Ground', 680: 'Fighting', 681: 'Fighting', 682: 'Dragon', 683: 'Ground', 684: 'Ground', 685: 'Dark', 686: 'Dark', 687: 'Normal', 688: 'Normal', 689: 'Normal', 690: 'Dark', 691: 'Dark', 692: 'Fire', 693: 'Bug', 694: 'Dark', 695: 'Dark', 696: 'Dark', 697: 'Bug', 698: 'Bug', 699: 'Steel', 700: 'Rock', 701: 'Grass', 702: 'Flying', 703: 'Flying', 704: 'Electric', 705: 'Electric', 706: 'Dragon', 707: 'Dragon', 708: 'Ground', 709: 'Ground', 710: 'Dragon', 711: 'Dragon', 712: 'Dragon', 713: 'Water', 714: 'Water', 715: 'Normal', 716: 'Normal', 717: 'Bug', 718: 'Grass', 719: 'Grass', 720: 'Grass', 721: 'Fire', 722: 'Fire', 723: 'Fire', 724: 'Water', 725: 'Water', 726: 'Water', 727: 'Normal', 728: 'Normal', 729: 'Normal', 730: 'Fire', 731: 'Fire', 732: 'Bug', 733: 'Bug', 734: 'Bug', 735: 'Fire', 736: 'Fire', 737: 'Fairy', 738: 'Fairy', 739: 'Fairy', 740: 'Grass', 741: 'Grass', 742: 'Fighting', 743: 'Fighting', 744: 'Normal', 745: 'Psychic', 746: 'Psychic', 747: 'Psychic', 748: 'Steel', 749: 'Steel', 750: 'Steel', 751: 'Steel', 752: 'Fairy', 753: 'Fairy', 754: 'Fairy', 755: 'Fairy', 756: 'Dark', 757: 'Dark', 758: 'Rock', 759: 'Rock', 760: 'Poison', 761: 'Poison', 762: 'Water', 763: 'Water', 764: 'Electric', 765: 'Electric', 766: 'Rock', 767: 'Rock', 768: 'Rock', 769: 'Rock', 770: 'Fairy', 771: 'Fighting', 772: 'Electric', 773: 'Rock', 774: 'Dragon', 775: 'Dragon', 776: 'Dragon', 777: 'Steel', 778: 'Ghost', 779: 'Ghost', 780: 'Ghost', 781: 'Ghost', 782: 'Ghost', 783: 'Ghost', 784: 'Ghost', 785: 'Ghost', 786: 'Ghost', 787: 'Ghost', 788: 'Ice', 789: 'Ice', 790: 'Flying', 791: 'Flying', 792: 'Fairy', 793: 'Dark', 794: 'Dragon', 795: 'Rock', 796: 'Rock', 797: 'Psychic', 798: 'Psychic', 799: 'Fire'}, 'Type 2': {0: 'Poison', 1: 'Poison', 2: 'Poison', 3: 'Poison', 4: nan, 5: nan, 6: 'Flying', 7: 'Dragon', 8: 'Flying', 9: nan, 10: nan, 11: nan, 12: nan, 13: nan, 14: nan, 15: 'Flying', 16: 'Poison', 17: 'Poison', 18: 'Poison', 19: 'Poison', 20: 'Flying', 21: 'Flying', 22: 'Flying', 23: 'Flying', 24: nan, 25: nan, 26: 'Flying', 27: 'Flying', 28: nan, 29: nan, 30: nan, 31: nan, 32: nan, 33: nan, 34: nan, 35: nan, 36: 'Ground', 37: nan, 38: nan, 39: 'Ground', 40: nan, 41: nan, 42: nan, 43: nan, 44: 'Fairy', 45: 'Fairy', 46: 'Flying', 47: 'Flying', 48: 'Poison', 49: 'Poison', 50: 'Poison', 51: 'Grass', 52: 'Grass', 53: 'Poison', 54: 'Poison', 55: nan, 56: nan, 57: nan, 58: nan, 59: nan, 60: nan, 61: nan, 62: nan, 63: nan, 64: nan, 65: nan, 66: nan, 67: 'Fighting', 68: nan, 69: nan, 70: nan, 71: nan, 72: nan, 73: nan, 74: nan, 75: 'Poison', 76: 'Poison', 77: 'Poison', 78: 'Poison', 79: 'Poison', 80: 'Ground', 81: 'Ground', 82: 'Ground', 83: nan, 84: nan, 85: 'Psychic', 86: 'Psychic', 87: 'Psychic', 88: 'Steel', 89: 'Steel', 90: 'Flying', 91: 'Flying', 92: 'Flying', 93: nan, 94: 'Ice', 95: nan, 96: nan, 97: nan, 98: 'Ice', 99: 'Poison', 100: 'Poison', 101: 'Poison', 102: 'Poison', 103: 'Ground', 104: nan, 105: nan, 106: nan, 107: nan, 108: nan, 109: nan, 110: 'Psychic', 111: 'Psychic', 112: nan, 113: nan, 114: nan, 115: nan, 116: nan, 117: nan, 118: nan, 119: 'Rock', 120: 'Rock', 121: nan, 122: nan, 123: nan, 124: nan, 125: nan, 126: nan, 127: nan, 128: nan, 129: nan, 130: 'Psychic', 131: 'Fairy', 132: 'Flying', 133: 'Psychic', 134: nan, 135: nan, 136: nan, 137: 'Flying', 138: nan, 139: nan, 140: 'Flying', 141: 'Dark', 142: 'Ice', 143: nan, 144: nan, 145: nan, 146: nan, 147: nan, 148: nan, 149: 'Water', 150: 'Water', 151: 'Water', 152: 'Water', 153: 'Flying', 154: 'Flying', 155: nan, 156: 'Flying', 157: 'Flying', 158: 'Flying', 159: nan, 160: nan, 161: 'Flying', 162: nan, 163: 'Fighting', 164: nan, 165: nan, 166: nan, 167: nan, 168: nan, 169: nan, 170: nan, 171: nan, 172: nan, 173: nan, 174: nan, 175: nan, 176: nan, 177: 'Flying', 178: 'Flying', 179: 'Flying', 180: 'Flying', 181: 'Poison', 182: 'Poison', 183: 'Flying', 184: 'Electric', 185: 'Electric', 186: nan, 187: nan, 188: 'Fairy', 189: nan, 190: 'Flying', 191: 'Flying', 192: 'Flying', 193: nan, 194: nan, 195: nan, 196: 'Dragon', 197: nan, 198: 'Fairy', 199: 'Fairy', 200: nan, 201: nan, 202: 'Flying', 203: 'Flying', 204: 'Flying', 205: nan, 206: nan, 207: nan, 208: 'Flying', 209: 'Ground', 210: 'Ground', 211: nan, 212: nan, 213: 'Flying', 214: 'Psychic', 215: nan, 216: nan, 217: nan, 218: 'Psychic', 219: nan, 220: 'Steel', 221: nan, 222: 'Flying', 223: 'Ground', 224: 'Ground', 225: nan, 226: nan, 227: 'Poison', 228: 'Steel', 229: 'Steel', 230: 'Rock', 231: 'Fighting', 232: 'Fighting', 233: 'Ice', 234: nan, 235: nan, 236: nan, 237: 'Rock', 238: 'Ground', 239: 'Ground', 240: 'Rock', 241: nan, 242: nan, 243: 'Flying', 244: 'Flying', 245: 'Flying', 246: 'Fire', 247: 'Fire', 248: 'Fire', 249: 'Dragon', 250: nan, 251: nan, 252: nan, 253: nan, 254: nan, 255: nan, 256: nan, 257: 'Psychic', 258: nan, 259: nan, 260: nan, 261: nan, 262: nan, 263: nan, 264: nan, 265: 'Ground', 266: 'Ground', 267: 'Dark', 268: 'Dark', 269: 'Flying', 270: 'Flying', 271: 'Grass', 272: nan, 273: nan, 274: nan, 275: 'Dragon', 276: nan, 277: 'Fighting', 278: 'Fighting', 279: 'Fighting', 280: nan, 281: 'Ground', 282: 'Ground', 283: 'Ground', 284: nan, 285: nan, 286: nan, 287: nan, 288: nan, 289: nan, 290: 'Flying', 291: nan, 292: 'Poison', 293: 'Grass', 294: 'Grass', 295: 'Grass', 296: nan, 297: 'Dark', 298: 'Dark', 299: 'Flying', 300: 'Flying', 301: 'Flying', 302: 'Flying', 303: 'Fairy', 304: 'Fairy', 305: 'Fairy', 306: 'Fairy', 307: 'Water', 308: 'Flying', 309: nan, 310: 'Fighting', 311: nan, 312: nan, 313: nan, 314: 'Ground', 315: 'Flying', 316: 'Ghost', 317: nan, 318: nan, 319: nan, 320: nan, 321: nan, 322: 'Fairy', 323: nan, 324: nan, 325: nan, 326: 'Ghost', 327: 'Ghost', 328: 'Fairy', 329: 'Fairy', 330: 'Rock', 331: 'Rock', 332: 'Rock', 333: nan, 334: 'Psychic', 335: 'Psychic', 336: 'Psychic', 337: nan, 338: nan, 339: nan, 340: nan, 341: nan, 342: nan, 343: nan, 344: 'Poison', 345: nan, 346: nan, 347: 'Dark', 348: 'Dark', 349: 'Dark', 350: nan, 351: nan, 352: 'Ground', 353: 'Ground', 354: 'Ground', 355: nan, 356: nan, 357: nan, 358: nan, 359: nan, 360: 'Dragon', 361: 'Dragon', 362: nan, 363: 'Dark', 364: 'Flying', 365: 'Flying', 366: 'Fairy', 367: nan, 368: nan, 369: 'Psychic', 370: 'Psychic', 371: 'Ground', 372: 'Ground', 373: nan, 374: 'Dark', 375: 'Psychic', 376: 'Psychic', 377: 'Grass', 378: 'Grass', 379: 'Bug', 380: 'Bug', 381: nan, 382: nan, 383: nan, 384: nan, 385: nan, 386: nan, 387: nan, 388: nan, 389: nan, 390: 'Flying', 391: nan, 392: nan, 393: nan, 394: nan, 395: nan, 396: nan, 397: nan, 398: 'Water', 399: 'Water', 400: 'Water', 401: nan, 402: nan, 403: nan, 404: 'Rock', 405: nan, 406: nan, 407: nan, 408: 'Flying', 409: 'Flying', 410: 'Psychic', 411: 'Psychic', 412: 'Psychic', 413: 'Psychic', 414: nan, 415: nan, 416: nan, 417: 'Psychic', 418: 'Psychic', 419: 'Psychic', 420: 'Psychic', 421: nan, 422: nan, 423: nan, 424: 'Fire', 425: 'Flying', 426: 'Flying', 427: 'Psychic', 428: nan, 429: nan, 430: nan, 431: nan, 432: nan, 433: nan, 434: 'Ground', 435: nan, 436: 'Fighting', 437: 'Fighting', 438: nan, 439: nan, 440: 'Steel', 441: 'Flying', 442: 'Flying', 443: 'Flying', 444: nan, 445: 'Water', 446: nan, 447: nan, 448: nan, 449: nan, 450: nan, 451: 'Poison', 452: 'Poison', 453: nan, 454: nan, 455: 'Steel', 456: 'Steel', 457: nan, 458: 'Grass', 459: 'Ground', 460: 'Steel', 461: 'Flying', 462: 'Flying', 463: 'Flying', 464: nan, 465: nan, 466: nan, 467: nan, 468: nan, 469: nan, 470: 'Ground', 471: nan, 472: 'Flying', 473: 'Flying', 474: nan, 475: nan, 476: 'Fighting', 477: nan, 478: 'Flying', 479: nan, 480: nan, 481: nan, 482: 'Dark', 483: 'Dark', 484: 'Psychic', 485: 'Psychic', 486: nan, 487: 'Fairy', 488: nan, 489: 'Flying', 490: 'Dark', 491: 'Ground', 492: 'Ground', 493: 'Ground', 494: 'Ground', 495: nan, 496: nan, 497: 'Steel', 498: 'Steel', 499: nan, 500: nan, 501: 'Bug', 502: 'Dark', 503: 'Fighting', 504: 'Fighting', 505: nan, 506: nan, 507: nan, 508: 'Flying', 509: 'Ice', 510: 'Ice', 511: 'Ice', 512: 'Ice', 513: 'Steel', 514: nan, 515: 'Rock', 516: nan, 517: nan, 518: nan, 519: 'Flying', 520: 'Flying', 521: nan, 522: nan, 523: 'Flying', 524: 'Ground', 525: nan, 526: 'Fighting', 527: 'Fighting', 528: 'Steel', 529: nan, 530: 'Ghost', 531: 'Ghost', 532: 'Fire', 533: 'Water', 534: 'Ice', 535: 'Flying', 536: 'Grass', 537: nan, 538: nan, 539: nan, 540: 'Dragon', 541: 'Dragon', 542: 'Steel', 543: nan, 544: 'Dragon', 545: 'Dragon', 546: nan, 547: nan, 548: nan, 549: nan, 550: nan, 551: 'Flying', 552: nan, 553: 'Fire', 554: nan, 555: nan, 556: nan, 557: nan, 558: 'Fighting', 559: 'Fighting', 560: nan, 561: nan, 562: nan, 563: nan, 564: nan, 565: nan, 566: nan, 567: nan, 568: nan, 569: nan, 570: nan, 571: nan, 572: nan, 573: nan, 574: nan, 575: nan, 576: nan, 577: nan, 578: 'Flying', 579: 'Flying', 580: 'Flying', 581: nan, 582: nan, 583: nan, 584: nan, 585: nan, 586: 'Flying', 587: 'Flying', 588: nan, 589: 'Steel', 590: nan, 591: 'Fairy', 592: nan, 593: nan, 594: nan, 595: nan, 596: 'Ground', 597: 'Ground', 598: nan, 599: nan, 600: 'Grass', 601: 'Grass', 602: 'Grass', 603: 'Poison', 604: 'Poison', 605: 'Poison', 606: 'Fairy', 607: 'Fairy', 608: nan, 609: nan, 610: nan, 611: 'Dark', 612: 'Dark', 613: 'Dark', 614: nan, 615: nan, 616: 'Psychic', 617: nan, 618: 'Rock', 619: 'Rock', 620: 'Fighting', 621: 'Fighting', 622: 'Flying', 623: nan, 624: nan, 625: 'Rock', 626: 'Rock', 627: 'Flying', 628: 'Flying', 629: nan, 630: nan, 631: nan, 632: nan, 633: nan, 634: nan, 635: nan, 636: nan, 637: nan, 638: nan, 639: nan, 640: nan, 641: 'Flying', 642: 'Flying', 643: nan, 644: nan, 645: nan, 646: 'Grass', 647: 'Grass', 648: 'Flying', 649: nan, 650: 'Steel', 651: 'Poison', 652: 'Poison', 653: 'Ghost', 654: 'Ghost', 655: nan, 656: 'Electric', 657: 'Electric', 658: 'Steel', 659: 'Steel', 660: nan, 661: nan, 662: nan, 663: nan, 664: nan, 665: nan, 666: nan, 667: nan, 668: 'Fire', 669: 'Fire', 670: 'Fire', 671: nan, 672: nan, 673: nan, 674: nan, 675: nan, 676: nan, 677: nan, 678: nan, 679: 'Electric', 680: nan, 681: nan, 682: nan, 683: 'Ghost', 684: 'Ghost', 685: 'Steel', 686: 'Steel', 687: nan, 688: 'Flying', 689: 'Flying', 690: 'Flying', 691: 'Flying', 692: nan, 693: 'Steel', 694: 'Dragon', 695: 'Dragon', 696: 'Dragon', 697: 'Fire', 698: 'Fire', 699: 'Fighting', 700: 'Fighting', 701: 'Fighting', 702: nan, 703: nan, 704: 'Flying', 705: 'Flying', 706: 'Fire', 707: 'Electric', 708: 'Flying', 709: 'Flying', 710: 'Ice', 711: 'Ice', 712: 'Ice', 713: 'Fighting', 714: 'Fighting', 715: 'Psychic', 716: 'Fighting', 717: 'Steel', 718: nan, 719: nan, 720: 'Fighting', 721: nan, 722: nan, 723: 'Psychic', 724: nan, 725: nan, 726: 'Dark', 727: nan, 728: 'Ground', 729: 'Flying', 730: 'Flying', 731: 'Flying', 732: nan, 733: nan, 734: 'Flying', 735: 'Normal', 736: 'Normal', 737: nan, 738: nan, 739: nan, 740: nan, 741: nan, 742: nan, 743: 'Dark', 744: nan, 745: nan, 746: nan, 747: nan, 748: 'Ghost', 749: 'Ghost', 750: 'Ghost', 751: 'Ghost', 752: nan, 753: nan, 754: nan, 755: nan, 756: 'Psychic', 757: 'Psychic', 758: 'Water', 759: 'Water', 760: 'Water', 761: 'Dragon', 762: nan, 763: nan, 764: 'Normal', 765: 'Normal', 766: 'Dragon', 767: 'Dragon', 768: 'Ice', 769: 'Ice', 770: nan, 771: 'Flying', 772: 'Fairy', 773: 'Fairy', 774: nan, 775: nan, 776: nan, 777: 'Fairy', 778: 'Grass', 779: 'Grass', 780: 'Grass', 781: 'Grass', 782: 'Grass', 783: 'Grass', 784: 'Grass', 785: 'Grass', 786: 'Grass', 787: 'Grass', 788: nan, 789: nan, 790: 'Dragon', 791: 'Dragon', 792: nan, 793: 'Flying', 794: 'Ground', 795: 'Fairy', 796: 'Fairy', 797: 'Ghost', 798: 'Dark', 799: 'Water'}, 'Total': {0: 318, 1: 405, 2: 525, 3: 625, 4: 309, 5: 405, 6: 534, 7: 634, 8: 634, 9: 314, 10: 405, 11: 530, 12: 630, 13: 195, 14: 205, 15: 395, 16: 195, 17: 205, 18: 395, 19: 495, 20: 251, 21: 349, 22: 479, 23: 579, 24: 253, 25: 413, 26: 262, 27: 442, 28: 288, 29: 438, 30: 320, 31: 485, 32: 300, 33: 450, 34: 275, 35: 365, 36: 505, 37: 273, 38: 365, 39: 505, 40: 323, 41: 483, 42: 299, 43: 505, 44: 270, 45: 435, 46: 245, 47: 455, 48: 320, 49: 395, 50: 490, 51: 285, 52: 405, 53: 305, 54: 450, 55: 265, 56: 405, 57: 290, 58: 440, 59: 320, 60: 500, 61: 305, 62: 455, 63: 350, 64: 555, 65: 300, 66: 385, 67: 510, 68: 310, 69: 400, 70: 500, 71: 590, 72: 305, 73: 405, 74: 505, 75: 300, 76: 390, 77: 490, 78: 335, 79: 515, 80: 300, 81: 390, 82: 495, 83: 410, 84: 500, 85: 315, 86: 490, 87: 590, 88: 325, 89: 465, 90: 352, 91: 310, 92: 460, 93: 325, 94: 475, 95: 325, 96: 500, 97: 305, 98: 525, 99: 310, 100: 405, 101: 500, 102: 600, 103: 385, 104: 328, 105: 483, 106: 325, 107: 475, 108: 330, 109: 480, 110: 325, 111: 520, 112: 320, 113: 425, 114: 455, 115: 455, 116: 385, 117: 340, 118: 490, 119: 345, 120: 485, 121: 450, 122: 435, 123: 490, 124: 590, 125: 295, 126: 440, 127: 320, 128: 450, 129: 340, 130: 520, 131: 460, 132: 500, 133: 455, 134: 490, 135: 495, 136: 500, 137: 600, 138: 490, 139: 200, 140: 540, 141: 640, 142: 535, 143: 288, 144: 325, 145: 525, 146: 525, 147: 525, 148: 395, 149: 355, 150: 495, 151: 355, 152: 495, 153: 515, 154: 615, 155: 540, 156: 580, 157: 580, 158: 580, 159: 300, 160: 420, 161: 600, 162: 680, 163: 780, 164: 780, 165: 600, 166: 318, 167: 405, 168: 525, 169: 309, 170: 405, 171: 534, 172: 314, 173: 405, 174: 530, 175: 215, 176: 415, 177: 262, 178: 442, 179: 265, 180: 390, 181: 250, 182: 390, 183: 535, 184: 330, 185: 460, 186: 205, 187: 218, 188: 210, 189: 245, 190: 405, 191: 320, 192: 470, 193: 280, 194: 365, 195: 510, 196: 610, 197: 490, 198: 250, 199: 420, 200: 410, 201: 500, 202: 250, 203: 340, 204: 460, 205: 360, 206: 180, 207: 425, 208: 390, 209: 210, 210: 430, 211: 525, 212: 525, 213: 405, 214: 490, 215: 435, 216: 336, 217: 405, 218: 455, 219: 290, 220: 465, 221: 415, 222: 430, 223: 510, 224: 610, 225: 300, 226: 450, 227: 430, 228: 500, 229: 600, 230: 505, 231: 500, 232: 600, 233: 430, 234: 330, 235: 500, 236: 250, 237: 410, 238: 250, 239: 450, 240: 380, 241: 300, 242: 480, 243: 330, 244: 465, 245: 465, 246: 330, 247: 500, 248: 600, 249: 540, 250: 330, 251: 500, 252: 515, 253: 465, 254: 250, 255: 210, 256: 455, 257: 305, 258: 360, 259: 365, 260: 490, 261: 540, 262: 580, 263: 580, 264: 580, 265: 300, 266: 410, 267: 600, 268: 700, 269: 680, 270: 680, 271: 600, 272: 310, 273: 405, 274: 530, 275: 630, 276: 310, 277: 405, 278: 530, 279: 630, 280: 310, 281: 405, 282: 535, 283: 635, 284: 220, 285: 420, 286: 240, 287: 420, 288: 195, 289: 205, 290: 395, 291: 205, 292: 385, 293: 220, 294: 340, 295: 480, 296: 220, 297: 340, 298: 480, 299: 270, 300: 430, 301: 270, 302: 430, 303: 198, 304: 278, 305: 518, 306: 618, 307: 269, 308: 414, 309: 295, 310: 460, 311: 280, 312: 440, 313: 670, 314: 266, 315: 456, 316: 236, 317: 240, 318: 360, 319: 490, 320: 237, 321: 474, 322: 190, 323: 375, 324: 260, 325: 380, 326: 380, 327: 480, 328: 380, 329: 480, 330: 330, 331: 430, 332: 530, 333: 630, 334: 280, 335: 410, 336: 510, 337: 295, 338: 475, 339: 575, 340: 405, 341: 405, 342: 400, 343: 400, 344: 400, 345: 302, 346: 467, 347: 305, 348: 460, 349: 560, 350: 400, 351: 500, 352: 305, 353: 460, 354: 560, 355: 470, 356: 330, 357: 470, 358: 360, 359: 290, 360: 340, 361: 520, 362: 335, 363: 475, 364: 310, 365: 490, 366: 590, 367: 458, 368: 458, 369: 440, 370: 440, 371: 288, 372: 468, 373: 308, 374: 468, 375: 300, 376: 500, 377: 355, 378: 495, 379: 355, 380: 495, 381: 200, 382: 540, 383: 420, 384: 440, 385: 295, 386: 455, 387: 555, 388: 295, 389: 455, 390: 460, 391: 425, 392: 465, 393: 565, 394: 260, 395: 300, 396: 480, 397: 580, 398: 290, 399: 410, 400: 530, 401: 345, 402: 485, 403: 485, 404: 485, 405: 330, 406: 300, 407: 420, 408: 600, 409: 700, 410: 300, 411: 420, 412: 600, 413: 700, 414: 580, 415: 580, 416: 580, 417: 600, 418: 700, 419: 600, 420: 700, 421: 670, 422: 770, 423: 670, 424: 770, 425: 680, 426: 780, 427: 600, 428: 600, 429: 600, 430: 600, 431: 600, 432: 318, 433: 405, 434: 525, 435: 309, 436: 405, 437: 534, 438: 314, 439: 405, 440: 530, 441: 245, 442: 340, 443: 485, 444: 250, 445: 410, 446: 194, 447: 384, 448: 263, 449: 363, 450: 523, 451: 280, 452: 515, 453: 350, 454: 495, 455: 350, 456: 495, 457: 224, 458: 424, 459: 424, 460: 424, 461: 424, 462: 244, 463: 474, 464: 405, 465: 330, 466: 495, 467: 275, 468: 450, 469: 325, 470: 475, 471: 482, 472: 348, 473: 498, 474: 350, 475: 480, 476: 580, 477: 495, 478: 505, 479: 310, 480: 452, 481: 285, 482: 329, 483: 479, 484: 300, 485: 500, 486: 290, 487: 310, 488: 220, 489: 411, 490: 485, 491: 300, 492: 410, 493: 600, 494: 700, 495: 390, 496: 285, 497: 525, 498: 625, 499: 330, 500: 525, 501: 330, 502: 500, 503: 300, 504: 490, 505: 454, 506: 330, 507: 460, 508: 345, 509: 334, 510: 494, 511: 594, 512: 510, 513: 535, 514: 515, 515: 535, 516: 535, 517: 540, 518: 540, 519: 545, 520: 515, 521: 525, 522: 525, 523: 510, 524: 530, 525: 535, 526: 518, 527: 618, 528: 525, 529: 525, 530: 480, 531: 440, 532: 520, 533: 520, 534: 520, 535: 520, 536: 520, 537: 580, 538: 580, 539: 580, 540: 680, 541: 680, 542: 600, 543: 670, 544: 680, 545: 680, 546: 600, 547: 480, 548: 600, 549: 600, 550: 600, 551: 600, 552: 720, 553: 600, 554: 308, 555: 413, 556: 528, 557: 308, 558: 418, 559: 528, 560: 308, 561: 413, 562: 528, 563: 255, 564: 420, 565: 275, 566: 370, 567: 500, 568: 281, 569: 446, 570: 316, 571: 498, 572: 316, 573: 498, 574: 316, 575: 498, 576: 292, 577: 487, 578: 264, 579: 358, 580: 488, 581: 295, 582: 497, 583: 280, 584: 390, 585: 515, 586: 313, 587: 425, 588: 328, 589: 508, 590: 445, 591: 545, 592: 305, 593: 405, 594: 505, 595: 294, 596: 384, 597: 509, 598: 465, 599: 465, 600: 310, 601: 380, 602: 500, 603: 260, 604: 360, 605: 485, 606: 280, 607: 480, 608: 280, 609: 480, 610: 460, 611: 292, 612: 351, 613: 519, 614: 315, 615: 480, 616: 540, 617: 461, 618: 325, 619: 475, 620: 348, 621: 488, 622: 490, 623: 303, 624: 483, 625: 355, 626: 495, 627: 401, 628: 567, 629: 329, 630: 474, 631: 330, 632: 510, 633: 300, 634: 470, 635: 290, 636: 390, 637: 490, 638: 290, 639: 370, 640: 490, 641: 305, 642: 473, 643: 305, 644: 395, 645: 535, 646: 335, 647: 475, 648: 428, 649: 315, 650: 495, 651: 294, 652: 464, 653: 335, 654: 480, 655: 470, 656: 319, 657: 472, 658: 305, 659: 489, 660: 300, 661: 440, 662: 520, 663: 275, 664: 405, 665: 515, 666: 335, 667: 485, 668: 275, 669: 370, 670: 520, 671: 320, 672: 410, 673: 540, 674: 305, 675: 485, 676: 485, 677: 305, 678: 495, 679: 471, 680: 350, 681: 510, 682: 485, 683: 303, 684: 483, 685: 340, 686: 490, 687: 490, 688: 350, 689: 510, 690: 370, 691: 510, 692: 484, 693: 484, 694: 300, 695: 420, 696: 600, 697: 360, 698: 550, 699: 580, 700: 580, 701: 580, 702: 580, 703: 580, 704: 580, 705: 580, 706: 680, 707: 680, 708: 600, 709: 600, 710: 660, 711: 700, 712: 700, 713: 580, 714: 580, 715: 600, 716: 600, 717: 600, 718: 313, 719: 405, 720: 530, 721: 307, 722: 409, 723: 534, 724: 314, 725: 405, 726: 530, 727: 237, 728: 423, 729: 278, 730: 382, 731: 499, 732: 200, 733: 213, 734: 411, 735: 369, 736: 507, 737: 303, 738: 371, 739: 552, 740: 350, 741: 531, 742: 348, 743: 495, 744: 472, 745: 355, 746: 466, 747: 466, 748: 325, 749: 448, 750: 520, 751: 520, 752: 341, 753: 462, 754: 341, 755: 480, 756: 288, 757: 482, 758: 306, 759: 500, 760: 320, 761: 494, 762: 330, 763: 500, 764: 289, 765: 481, 766: 362, 767: 521, 768: 362, 769: 521, 770: 525, 771: 500, 772: 431, 773: 500, 774: 300, 775: 452, 776: 600, 777: 470, 778: 309, 779: 474, 780: 335, 781: 335, 782: 335, 783: 335, 784: 494, 785: 494, 786: 494, 787: 494, 788: 304, 789: 514, 790: 245, 791: 535, 792: 680, 793: 680, 794: 600, 795: 600, 796: 700, 797: 600, 798: 680, 799: 600}, 'HP': {0: 45, 1: 60, 2: 80, 3: 80, 4: 39, 5: 58, 6: 78, 7: 78, 8: 78, 9: 44, 10: 59, 11: 79, 12: 79, 13: 45, 14: 50, 15: 60, 16: 40, 17: 45, 18: 65, 19: 65, 20: 40, 21: 63, 22: 83, 23: 83, 24: 30, 25: 55, 26: 40, 27: 65, 28: 35, 29: 60, 30: 35, 31: 60, 32: 50, 33: 75, 34: 55, 35: 70, 36: 90, 37: 46, 38: 61, 39: 81, 40: 70, 41: 95, 42: 38, 43: 73, 44: 115, 45: 140, 46: 40, 47: 75, 48: 45, 49: 60, 50: 75, 51: 35, 52: 60, 53: 60, 54: 70, 55: 10, 56: 35, 57: 40, 58: 65, 59: 50, 60: 80, 61: 40, 62: 65, 63: 55, 64: 90, 65: 40, 66: 65, 67: 90, 68: 25, 69: 40, 70: 55, 71: 55, 72: 70, 73: 80, 74: 90, 75: 50, 76: 65, 77: 80, 78: 40, 79: 80, 80: 40, 81: 55, 82: 80, 83: 50, 84: 65, 85: 90, 86: 95, 87: 95, 88: 25, 89: 50, 90: 52, 91: 35, 92: 60, 93: 65, 94: 90, 95: 80, 96: 105, 97: 30, 98: 50, 99: 30, 100: 45, 101: 60, 102: 60, 103: 35, 104: 60, 105: 85, 106: 30, 107: 55, 108: 40, 109: 60, 110: 60, 111: 95, 112: 50, 113: 60, 114: 50, 115: 50, 116: 90, 117: 40, 118: 65, 119: 80, 120: 105, 121: 250, 122: 65, 123: 105, 124: 105, 125: 30, 126: 55, 127: 45, 128: 80, 129: 30, 130: 60, 131: 40, 132: 70, 133: 65, 134: 65, 135: 65, 136: 65, 137: 65, 138: 75, 139: 20, 140: 95, 141: 95, 142: 130, 143: 48, 144: 55, 145: 130, 146: 65, 147: 65, 148: 65, 149: 35, 150: 70, 151: 30, 152: 60, 153: 80, 154: 80, 155: 160, 156: 90, 157: 90, 158: 90, 159: 41, 160: 61, 161: 91, 162: 106, 163: 106, 164: 106, 165: 100, 166: 45, 167: 60, 168: 80, 169: 39, 170: 58, 171: 78, 172: 50, 173: 65, 174: 85, 175: 35, 176: 85, 177: 60, 178: 100, 179: 40, 180: 55, 181: 40, 182: 70, 183: 85, 184: 75, 185: 125, 186: 20, 187: 50, 188: 90, 189: 35, 190: 55, 191: 40, 192: 65, 193: 55, 194: 70, 195: 90, 196: 90, 197: 75, 198: 70, 199: 100, 200: 70, 201: 90, 202: 35, 203: 55, 204: 75, 205: 55, 206: 30, 207: 75, 208: 65, 209: 55, 210: 95, 211: 65, 212: 95, 213: 60, 214: 95, 215: 60, 216: 48, 217: 190, 218: 70, 219: 50, 220: 75, 221: 100, 222: 65, 223: 75, 224: 75, 225: 60, 226: 90, 227: 65, 228: 70, 229: 70, 230: 20, 231: 80, 232: 80, 233: 55, 234: 60, 235: 90, 236: 40, 237: 50, 238: 50, 239: 100, 240: 55, 241: 35, 242: 75, 243: 45, 244: 65, 245: 65, 246: 45, 247: 75, 248: 75, 249: 75, 250: 90, 251: 90, 252: 85, 253: 73, 254: 55, 255: 35, 256: 50, 257: 45, 258: 45, 259: 45, 260: 95, 261: 255, 262: 90, 263: 115, 264: 100, 265: 50, 266: 70, 267: 100, 268: 100, 269: 106, 270: 106, 271: 100, 272: 40, 273: 50, 274: 70, 275: 70, 276: 45, 277: 60, 278: 80, 279: 80, 280: 50, 281: 70, 282: 100, 283: 100, 284: 35, 285: 70, 286: 38, 287: 78, 288: 45, 289: 50, 290: 60, 291: 50, 292: 60, 293: 40, 294: 60, 295: 80, 296: 40, 297: 70, 298: 90, 299: 40, 300: 60, 301: 40, 302: 60, 303: 28, 304: 38, 305: 68, 306: 68, 307: 40, 308: 70, 309: 60, 310: 60, 311: 60, 312: 80, 313: 150, 314: 31, 315: 61, 316: 1, 317: 64, 318: 84, 319: 104, 320: 72, 321: 144, 322: 50, 323: 30, 324: 50, 325: 70, 326: 50, 327: 50, 328: 50, 329: 50, 330: 50, 331: 60, 332: 70, 333: 70, 334: 30, 335: 60, 336: 60, 337: 40, 338: 70, 339: 70, 340: 60, 341: 60, 342: 65, 343: 65, 344: 50, 345: 70, 346: 100, 347: 45, 348: 70, 349: 70, 350: 130, 351: 170, 352: 60, 353: 70, 354: 70, 355: 70, 356: 60, 357: 80, 358: 60, 359: 45, 360: 50, 361: 80, 362: 50, 363: 70, 364: 45, 365: 75, 366: 75, 367: 73, 368: 73, 369: 70, 370: 70, 371: 50, 372: 110, 373: 43, 374: 63, 375: 40, 376: 60, 377: 66, 378: 86, 379: 45, 380: 75, 381: 20, 382: 95, 383: 70, 384: 60, 385: 44, 386: 64, 387: 64, 388: 20, 389: 40, 390: 99, 391: 65, 392: 65, 393: 65, 394: 95, 395: 50, 396: 80, 397: 80, 398: 70, 399: 90, 400: 110, 401: 35, 402: 55, 403: 55, 404: 100, 405: 43, 406: 45, 407: 65, 408: 95, 409: 95, 410: 40, 411: 60, 412: 80, 413: 80, 414: 80, 415: 80, 416: 80, 417: 80, 418: 80, 419: 80, 420: 80, 421: 100, 422: 100, 423: 100, 424: 100, 425: 105, 426: 105, 427: 100, 428: 50, 429: 50, 430: 50, 431: 50, 432: 55, 433: 75, 434: 95, 435: 44, 436: 64, 437: 76, 438: 53, 439: 64, 440: 84, 441: 40, 442: 55, 443: 85, 444: 59, 445: 79, 446: 37, 447: 77, 448: 45, 449: 60, 450: 80, 451: 40, 452: 60, 453: 67, 454: 97, 455: 30, 456: 60, 457: 40, 458: 60, 459: 60, 460: 60, 461: 70, 462: 30, 463: 70, 464: 60, 465: 55, 466: 85, 467: 45, 468: 70, 469: 76, 470: 111, 471: 75, 472: 90, 473: 150, 474: 55, 475: 65, 476: 65, 477: 60, 478: 100, 479: 49, 480: 71, 481: 45, 482: 63, 483: 103, 484: 57, 485: 67, 486: 50, 487: 20, 488: 100, 489: 76, 490: 50, 491: 58, 492: 68, 493: 108, 494: 108, 495: 135, 496: 40, 497: 70, 498: 70, 499: 68, 500: 108, 501: 40, 502: 70, 503: 48, 504: 83, 505: 74, 506: 49, 507: 69, 508: 45, 509: 60, 510: 90, 511: 90, 512: 70, 513: 70, 514: 110, 515: 115, 516: 100, 517: 75, 518: 75, 519: 85, 520: 86, 521: 65, 522: 65, 523: 75, 524: 110, 525: 85, 526: 68, 527: 68, 528: 60, 529: 45, 530: 70, 531: 50, 532: 50, 533: 50, 534: 50, 535: 50, 536: 50, 537: 75, 538: 80, 539: 75, 540: 100, 541: 90, 542: 91, 543: 110, 544: 150, 545: 150, 546: 120, 547: 80, 548: 100, 549: 70, 550: 100, 551: 100, 552: 120, 553: 100, 554: 45, 555: 60, 556: 75, 557: 65, 558: 90, 559: 110, 560: 55, 561: 75, 562: 95, 563: 45, 564: 60, 565: 45, 566: 65, 567: 85, 568: 41, 569: 64, 570: 50, 571: 75, 572: 50, 573: 75, 574: 50, 575: 75, 576: 76, 577: 116, 578: 50, 579: 62, 580: 80, 581: 45, 582: 75, 583: 55, 584: 70, 585: 85, 586: 55, 587: 67, 588: 60, 589: 110, 590: 103, 591: 103, 592: 75, 593: 85, 594: 105, 595: 50, 596: 75, 597: 105, 598: 120, 599: 75, 600: 45, 601: 55, 602: 75, 603: 30, 604: 40, 605: 60, 606: 40, 607: 60, 608: 45, 609: 70, 610: 70, 611: 50, 612: 60, 613: 95, 614: 70, 615: 105, 616: 105, 617: 75, 618: 50, 619: 70, 620: 50, 621: 65, 622: 72, 623: 38, 624: 58, 625: 54, 626: 74, 627: 55, 628: 75, 629: 50, 630: 80, 631: 40, 632: 60, 633: 55, 634: 75, 635: 45, 636: 60, 637: 70, 638: 45, 639: 65, 640: 110, 641: 62, 642: 75, 643: 36, 644: 51, 645: 71, 646: 60, 647: 80, 648: 55, 649: 50, 650: 70, 651: 69, 652: 114, 653: 55, 654: 100, 655: 165, 656: 50, 657: 70, 658: 44, 659: 74, 660: 40, 661: 60, 662: 60, 663: 35, 664: 65, 665: 85, 666: 55, 667: 75, 668: 50, 669: 60, 670: 60, 671: 46, 672: 66, 673: 76, 674: 55, 675: 95, 676: 70, 677: 50, 678: 80, 679: 109, 680: 45, 681: 65, 682: 77, 683: 59, 684: 89, 685: 45, 686: 65, 687: 95, 688: 70, 689: 100, 690: 70, 691: 110, 692: 85, 693: 58, 694: 52, 695: 72, 696: 92, 697: 55, 698: 85, 699: 91, 700: 91, 701: 91, 702: 79, 703: 79, 704: 79, 705: 79, 706: 100, 707: 100, 708: 89, 709: 89, 710: 125, 711: 125, 712: 125, 713: 91, 714: 91, 715: 100, 716: 100, 717: 71, 718: 56, 719: 61, 720: 88, 721: 40, 722: 59, 723: 75, 724: 41, 725: 54, 726: 72, 727: 38, 728: 85, 729: 45, 730: 62, 731: 78, 732: 38, 733: 45, 734: 80, 735: 62, 736: 86, 737: 44, 738: 54, 739: 78, 740: 66, 741: 123, 742: 67, 743: 95, 744: 75, 745: 62, 746: 74, 747: 74, 748: 45, 749: 59, 750: 60, 751: 60, 752: 78, 753: 101, 754: 62, 755: 82, 756: 53, 757: 86, 758: 42, 759: 72, 760: 50, 761: 65, 762: 50, 763: 71, 764: 44, 765: 62, 766: 58, 767: 82, 768: 77, 769: 123, 770: 95, 771: 78, 772: 67, 773: 50, 774: 45, 775: 68, 776: 90, 777: 57, 778: 43, 779: 85, 780: 49, 781: 44, 782: 54, 783: 59, 784: 65, 785: 55, 786: 75, 787: 85, 788: 55, 789: 95, 790: 40, 791: 85, 792: 126, 793: 126, 794: 108, 795: 50, 796: 50, 797: 80, 798: 80, 799: 80}, 'Attack': {0: 49, 1: 62, 2: 82, 3: 100, 4: 52, 5: 64, 6: 84, 7: 130, 8: 104, 9: 48, 10: 63, 11: 83, 12: 103, 13: 30, 14: 20, 15: 45, 16: 35, 17: 25, 18: 90, 19: 150, 20: 45, 21: 60, 22: 80, 23: 80, 24: 56, 25: 81, 26: 60, 27: 90, 28: 60, 29: 85, 30: 55, 31: 90, 32: 75, 33: 100, 34: 47, 35: 62, 36: 92, 37: 57, 38: 72, 39: 102, 40: 45, 41: 70, 42: 41, 43: 76, 44: 45, 45: 70, 46: 45, 47: 80, 48: 50, 49: 65, 50: 80, 51: 70, 52: 95, 53: 55, 54: 65, 55: 55, 56: 80, 57: 45, 58: 70, 59: 52, 60: 82, 61: 80, 62: 105, 63: 70, 64: 110, 65: 50, 66: 65, 67: 95, 68: 20, 69: 35, 70: 50, 71: 50, 72: 80, 73: 100, 74: 130, 75: 75, 76: 90, 77: 105, 78: 40, 79: 70, 80: 80, 81: 95, 82: 120, 83: 85, 84: 100, 85: 65, 86: 75, 87: 75, 88: 35, 89: 60, 90: 65, 91: 85, 92: 110, 93: 45, 94: 70, 95: 80, 96: 105, 97: 65, 98: 95, 99: 35, 100: 50, 101: 65, 102: 65, 103: 45, 104: 48, 105: 73, 106: 105, 107: 130, 108: 30, 109: 50, 110: 40, 111: 95, 112: 50, 113: 80, 114: 120, 115: 105, 116: 55, 117: 65, 118: 90, 119: 85, 120: 130, 121: 5, 122: 55, 123: 95, 124: 125, 125: 40, 126: 65, 127: 67, 128: 92, 129: 45, 130: 75, 131: 45, 132: 110, 133: 50, 134: 83, 135: 95, 136: 125, 137: 155, 138: 100, 139: 10, 140: 125, 141: 155, 142: 85, 143: 48, 144: 55, 145: 65, 146: 65, 147: 130, 148: 60, 149: 40, 150: 60, 151: 80, 152: 115, 153: 105, 154: 135, 155: 110, 156: 85, 157: 90, 158: 100, 159: 64, 160: 84, 161: 134, 162: 110, 163: 190, 164: 150, 165: 100, 166: 49, 167: 62, 168: 82, 169: 52, 170: 64, 171: 84, 172: 65, 173: 80, 174: 105, 175: 46, 176: 76, 177: 30, 178: 50, 179: 20, 180: 35, 181: 60, 182: 90, 183: 90, 184: 38, 185: 58, 186: 40, 187: 25, 188: 30, 189: 20, 190: 40, 191: 50, 192: 75, 193: 40, 194: 55, 195: 75, 196: 95, 197: 80, 198: 20, 199: 50, 200: 100, 201: 75, 202: 35, 203: 45, 204: 55, 205: 70, 206: 30, 207: 75, 208: 65, 209: 45, 210: 85, 211: 65, 212: 65, 213: 85, 214: 75, 215: 60, 216: 72, 217: 33, 218: 80, 219: 65, 220: 90, 221: 70, 222: 75, 223: 85, 224: 125, 225: 80, 226: 120, 227: 95, 228: 130, 229: 150, 230: 10, 231: 125, 232: 185, 233: 95, 234: 80, 235: 130, 236: 40, 237: 50, 238: 50, 239: 100, 240: 55, 241: 65, 242: 105, 243: 55, 244: 40, 245: 80, 246: 60, 247: 90, 248: 90, 249: 95, 250: 60, 251: 120, 252: 80, 253: 95, 254: 20, 255: 35, 256: 95, 257: 30, 258: 63, 259: 75, 260: 80, 261: 10, 262: 85, 263: 115, 264: 75, 265: 64, 266: 84, 267: 134, 268: 164, 269: 90, 270: 130, 271: 100, 272: 45, 273: 65, 274: 85, 275: 110, 276: 60, 277: 85, 278: 120, 279: 160, 280: 70, 281: 85, 282: 110, 283: 150, 284: 55, 285: 90, 286: 30, 287: 70, 288: 45, 289: 35, 290: 70, 291: 35, 292: 50, 293: 30, 294: 50, 295: 70, 296: 40, 297: 70, 298: 100, 299: 55, 300: 85, 301: 30, 302: 50, 303: 25, 304: 35, 305: 65, 306: 85, 307: 30, 308: 60, 309: 40, 310: 130, 311: 60, 312: 80, 313: 160, 314: 45, 315: 90, 316: 90, 317: 51, 318: 71, 319: 91, 320: 60, 321: 120, 322: 20, 323: 45, 324: 45, 325: 65, 326: 75, 327: 85, 328: 85, 329: 105, 330: 70, 331: 90, 332: 110, 333: 140, 334: 40, 335: 60, 336: 100, 337: 45, 338: 75, 339: 75, 340: 50, 341: 40, 342: 73, 343: 47, 344: 60, 345: 43, 346: 73, 347: 90, 348: 120, 349: 140, 350: 70, 351: 90, 352: 60, 353: 100, 354: 120, 355: 85, 356: 25, 357: 45, 358: 60, 359: 100, 360: 70, 361: 100, 362: 85, 363: 115, 364: 40, 365: 70, 366: 110, 367: 115, 368: 100, 369: 55, 370: 95, 371: 48, 372: 78, 373: 80, 374: 120, 375: 40, 376: 70, 377: 41, 378: 81, 379: 95, 380: 125, 381: 15, 382: 60, 383: 70, 384: 90, 385: 75, 386: 115, 387: 165, 388: 40, 389: 70, 390: 68, 391: 50, 392: 130, 393: 150, 394: 23, 395: 50, 396: 80, 397: 120, 398: 40, 399: 60, 400: 80, 401: 64, 402: 104, 403: 84, 404: 90, 405: 30, 406: 75, 407: 95, 408: 135, 409: 145, 410: 55, 411: 75, 412: 135, 413: 145, 414: 100, 415: 50, 416: 75, 417: 80, 418: 100, 419: 90, 420: 130, 421: 100, 422: 150, 423: 150, 424: 180, 425: 150, 426: 180, 427: 100, 428: 150, 429: 180, 430: 70, 431: 95, 432: 68, 433: 89, 434: 109, 435: 58, 436: 78, 437: 104, 438: 51, 439: 66, 440: 86, 441: 55, 442: 75, 443: 120, 444: 45, 445: 85, 446: 25, 447: 85, 448: 65, 449: 85, 450: 120, 451: 30, 452: 70, 453: 125, 454: 165, 455: 42, 456: 52, 457: 29, 458: 59, 459: 79, 460: 69, 461: 94, 462: 30, 463: 80, 464: 45, 465: 65, 466: 105, 467: 35, 468: 60, 469: 48, 470: 83, 471: 100, 472: 50, 473: 80, 474: 66, 475: 76, 476: 136, 477: 60, 478: 125, 479: 55, 480: 82, 481: 30, 482: 63, 483: 93, 484: 24, 485: 89, 486: 80, 487: 25, 488: 5, 489: 65, 490: 92, 491: 70, 492: 90, 493: 130, 494: 170, 495: 85, 496: 70, 497: 110, 498: 145, 499: 72, 500: 112, 501: 50, 502: 90, 503: 61, 504: 106, 505: 100, 506: 49, 507: 69, 508: 20, 509: 62, 510: 92, 511: 132, 512: 120, 513: 70, 514: 85, 515: 140, 516: 100, 517: 123, 518: 95, 519: 50, 520: 76, 521: 110, 522: 60, 523: 95, 524: 130, 525: 80, 526: 125, 527: 165, 528: 55, 529: 100, 530: 80, 531: 50, 532: 65, 533: 65, 534: 65, 535: 65, 536: 65, 537: 75, 538: 105, 539: 125, 540: 120, 541: 120, 542: 90, 543: 160, 544: 100, 545: 120, 546: 70, 547: 80, 548: 100, 549: 90, 550: 100, 551: 103, 552: 120, 553: 100, 554: 45, 555: 60, 556: 75, 557: 63, 558: 93, 559: 123, 560: 55, 561: 75, 562: 100, 563: 55, 564: 85, 565: 60, 566: 80, 567: 110, 568: 50, 569: 88, 570: 53, 571: 98, 572: 53, 573: 98, 574: 53, 575: 98, 576: 25, 577: 55, 578: 55, 579: 77, 580: 115, 581: 60, 582: 100, 583: 75, 584: 105, 585: 135, 586: 45, 587: 57, 588: 85, 589: 135, 590: 60, 591: 60, 592: 80, 593: 105, 594: 140, 595: 50, 596: 65, 597: 95, 598: 100, 599: 125, 600: 53, 601: 63, 602: 103, 603: 45, 604: 55, 605: 100, 606: 27, 607: 67, 608: 35, 609: 60, 610: 92, 611: 72, 612: 82, 613: 117, 614: 90, 615: 140, 616: 30, 617: 86, 618: 65, 619: 95, 620: 75, 621: 90, 622: 58, 623: 30, 624: 50, 625: 78, 626: 108, 627: 112, 628: 140, 629: 50, 630: 95, 631: 65, 632: 105, 633: 50, 634: 95, 635: 30, 636: 45, 637: 55, 638: 30, 639: 40, 640: 65, 641: 44, 642: 87, 643: 50, 644: 65, 645: 95, 646: 60, 647: 100, 648: 75, 649: 75, 650: 135, 651: 55, 652: 85, 653: 40, 654: 60, 655: 75, 656: 47, 657: 77, 658: 50, 659: 94, 660: 55, 661: 80, 662: 100, 663: 55, 664: 85, 665: 115, 666: 55, 667: 75, 668: 30, 669: 40, 670: 55, 671: 87, 672: 117, 673: 147, 674: 70, 675: 110, 676: 50, 677: 40, 678: 70, 679: 66, 680: 85, 681: 125, 682: 120, 683: 74, 684: 124, 685: 85, 686: 125, 687: 110, 688: 83, 689: 123, 690: 55, 691: 65, 692: 97, 693: 109, 694: 65, 695: 85, 696: 105, 697: 85, 698: 60, 699: 90, 700: 129, 701: 90, 702: 115, 703: 100, 704: 115, 705: 105, 706: 120, 707: 150, 708: 125, 709: 145, 710: 130, 711: 170, 712: 120, 713: 72, 714: 72, 715: 77, 716: 128, 717: 120, 718: 61, 719: 78, 720: 107, 721: 45, 722: 59, 723: 69, 724: 56, 725: 63, 726: 95, 727: 36, 728: 56, 729: 50, 730: 73, 731: 81, 732: 35, 733: 22, 734: 52, 735: 50, 736: 68, 737: 38, 738: 45, 739: 65, 740: 65, 741: 100, 742: 82, 743: 124, 744: 80, 745: 48, 746: 48, 747: 48, 748: 80, 749: 110, 750: 150, 751: 50, 752: 52, 753: 72, 754: 48, 755: 80, 756: 54, 757: 92, 758: 52, 759: 105, 760: 60, 761: 75, 762: 53, 763: 73, 764: 38, 765: 55, 766: 89, 767: 121, 768: 59, 769: 77, 770: 65, 771: 92, 772: 58, 773: 50, 774: 50, 775: 75, 776: 100, 777: 80, 778: 70, 779: 110, 780: 66, 781: 66, 782: 66, 783: 66, 784: 90, 785: 85, 786: 95, 787: 100, 788: 69, 789: 117, 790: 30, 791: 70, 792: 131, 793: 131, 794: 100, 795: 100, 796: 160, 797: 110, 798: 160, 799: 110}, 'Defense': {0: 49, 1: 63, 2: 83, 3: 123, 4: 43, 5: 58, 6: 78, 7: 111, 8: 78, 9: 65, 10: 80, 11: 100, 12: 120, 13: 35, 14: 55, 15: 50, 16: 30, 17: 50, 18: 40, 19: 40, 20: 40, 21: 55, 22: 75, 23: 80, 24: 35, 25: 60, 26: 30, 27: 65, 28: 44, 29: 69, 30: 40, 31: 55, 32: 85, 33: 110, 34: 52, 35: 67, 36: 87, 37: 40, 38: 57, 39: 77, 40: 48, 41: 73, 42: 40, 43: 75, 44: 20, 45: 45, 46: 35, 47: 70, 48: 55, 49: 70, 50: 85, 51: 55, 52: 80, 53: 50, 54: 60, 55: 25, 56: 50, 57: 35, 58: 60, 59: 48, 60: 78, 61: 35, 62: 60, 63: 45, 64: 80, 65: 40, 66: 65, 67: 95, 68: 15, 69: 30, 70: 45, 71: 65, 72: 50, 73: 70, 74: 80, 75: 35, 76: 50, 77: 65, 78: 35, 79: 65, 80: 100, 81: 115, 82: 130, 83: 55, 84: 70, 85: 65, 86: 110, 87: 180, 88: 70, 89: 95, 90: 55, 91: 45, 92: 70, 93: 55, 94: 80, 95: 50, 96: 75, 97: 100, 98: 180, 99: 30, 100: 45, 101: 60, 102: 80, 103: 160, 104: 45, 105: 70, 106: 90, 107: 115, 108: 50, 109: 70, 110: 80, 111: 85, 112: 95, 113: 110, 114: 53, 115: 79, 116: 75, 117: 95, 118: 120, 119: 95, 120: 120, 121: 5, 122: 115, 123: 80, 124: 100, 125: 70, 126: 95, 127: 60, 128: 65, 129: 55, 130: 85, 131: 65, 132: 80, 133: 35, 134: 57, 135: 57, 136: 100, 137: 120, 138: 95, 139: 55, 140: 79, 141: 109, 142: 80, 143: 48, 144: 50, 145: 60, 146: 60, 147: 60, 148: 70, 149: 100, 150: 125, 151: 90, 152: 105, 153: 65, 154: 85, 155: 65, 156: 100, 157: 85, 158: 90, 159: 45, 160: 65, 161: 95, 162: 90, 163: 100, 164: 70, 165: 100, 166: 65, 167: 80, 168: 100, 169: 43, 170: 58, 171: 78, 172: 64, 173: 80, 174: 100, 175: 34, 176: 64, 177: 30, 178: 50, 179: 30, 180: 50, 181: 40, 182: 70, 183: 80, 184: 38, 185: 58, 186: 15, 187: 28, 188: 15, 189: 65, 190: 85, 191: 45, 192: 70, 193: 40, 194: 55, 195: 85, 196: 105, 197: 95, 198: 50, 199: 80, 200: 115, 201: 75, 202: 40, 203: 50, 204: 70, 205: 55, 206: 30, 207: 55, 208: 45, 209: 45, 210: 85, 211: 60, 212: 110, 213: 42, 214: 80, 215: 60, 216: 48, 217: 58, 218: 65, 219: 90, 220: 140, 221: 70, 222: 105, 223: 200, 224: 230, 225: 50, 226: 75, 227: 75, 228: 100, 229: 140, 230: 230, 231: 75, 232: 115, 233: 55, 234: 50, 235: 75, 236: 40, 237: 120, 238: 40, 239: 80, 240: 85, 241: 35, 242: 75, 243: 45, 244: 70, 245: 140, 246: 30, 247: 50, 248: 90, 249: 95, 250: 60, 251: 120, 252: 90, 253: 62, 254: 35, 255: 35, 256: 95, 257: 15, 258: 37, 259: 37, 260: 105, 261: 10, 262: 75, 263: 85, 264: 115, 265: 50, 266: 70, 267: 110, 268: 150, 269: 130, 270: 90, 271: 100, 272: 35, 273: 45, 274: 65, 275: 75, 276: 40, 277: 60, 278: 70, 279: 80, 280: 50, 281: 70, 282: 90, 283: 110, 284: 35, 285: 70, 286: 41, 287: 61, 288: 35, 289: 55, 290: 50, 291: 55, 292: 70, 293: 30, 294: 50, 295: 70, 296: 50, 297: 40, 298: 60, 299: 30, 300: 60, 301: 30, 302: 100, 303: 25, 304: 35, 305: 65, 306: 65, 307: 32, 308: 62, 309: 60, 310: 80, 311: 60, 312: 80, 313: 100, 314: 90, 315: 45, 316: 45, 317: 23, 318: 43, 319: 63, 320: 30, 321: 60, 322: 40, 323: 135, 324: 45, 325: 65, 326: 75, 327: 125, 328: 85, 329: 125, 330: 100, 331: 140, 332: 180, 333: 230, 334: 55, 335: 75, 336: 85, 337: 40, 338: 60, 339: 80, 340: 40, 341: 50, 342: 55, 343: 55, 344: 45, 345: 53, 346: 83, 347: 20, 348: 40, 349: 70, 350: 35, 351: 45, 352: 40, 353: 70, 354: 100, 355: 140, 356: 35, 357: 65, 358: 60, 359: 45, 360: 50, 361: 80, 362: 40, 363: 60, 364: 60, 365: 90, 366: 110, 367: 60, 368: 60, 369: 65, 370: 85, 371: 43, 372: 73, 373: 65, 374: 85, 375: 55, 376: 105, 377: 77, 378: 97, 379: 50, 380: 100, 381: 20, 382: 79, 383: 70, 384: 70, 385: 35, 386: 65, 387: 75, 388: 90, 389: 130, 390: 83, 391: 70, 392: 60, 393: 60, 394: 48, 395: 50, 396: 80, 397: 80, 398: 50, 399: 70, 400: 90, 401: 85, 402: 105, 403: 105, 404: 130, 405: 55, 406: 60, 407: 100, 408: 80, 409: 130, 410: 80, 411: 100, 412: 130, 413: 150, 414: 200, 415: 100, 416: 150, 417: 90, 418: 120, 419: 80, 420: 100, 421: 90, 422: 90, 423: 140, 424: 160, 425: 90, 426: 100, 427: 100, 428: 50, 429: 20, 430: 160, 431: 90, 432: 64, 433: 85, 434: 105, 435: 44, 436: 52, 437: 71, 438: 53, 439: 68, 440: 88, 441: 30, 442: 50, 443: 70, 444: 40, 445: 60, 446: 41, 447: 51, 448: 34, 449: 49, 450: 79, 451: 35, 452: 65, 453: 40, 454: 60, 455: 118, 456: 168, 457: 45, 458: 85, 459: 105, 460: 95, 461: 50, 462: 42, 463: 102, 464: 70, 465: 35, 466: 55, 467: 45, 468: 70, 469: 48, 470: 68, 471: 66, 472: 34, 473: 44, 474: 44, 475: 84, 476: 94, 477: 60, 478: 52, 479: 42, 480: 64, 481: 50, 482: 47, 483: 67, 484: 86, 485: 116, 486: 95, 487: 45, 488: 5, 489: 45, 490: 108, 491: 45, 492: 65, 493: 95, 494: 115, 495: 40, 496: 40, 497: 70, 498: 88, 499: 78, 500: 118, 501: 90, 502: 110, 503: 40, 504: 65, 505: 72, 506: 56, 507: 76, 508: 50, 509: 50, 510: 75, 511: 105, 512: 65, 513: 115, 514: 95, 515: 130, 516: 125, 517: 67, 518: 67, 519: 95, 520: 86, 521: 130, 522: 110, 523: 125, 524: 80, 525: 70, 526: 65, 527: 95, 528: 145, 529: 135, 530: 70, 531: 77, 532: 107, 533: 107, 534: 107, 535: 107, 536: 107, 537: 130, 538: 105, 539: 70, 540: 120, 541: 100, 542: 106, 543: 110, 544: 120, 545: 100, 546: 120, 547: 80, 548: 100, 549: 90, 550: 100, 551: 75, 552: 120, 553: 100, 554: 55, 555: 75, 556: 95, 557: 45, 558: 55, 559: 65, 560: 45, 561: 60, 562: 85, 563: 39, 564: 69, 565: 45, 566: 65, 567: 90, 568: 37, 569: 50, 570: 48, 571: 63, 572: 48, 573: 63, 574: 48, 575: 63, 576: 45, 577: 85, 578: 50, 579: 62, 580: 80, 581: 32, 582: 63, 583: 85, 584: 105, 585: 130, 586: 43, 587: 55, 588: 40, 589: 60, 590: 86, 591: 126, 592: 55, 593: 85, 594: 95, 595: 40, 596: 55, 597: 75, 598: 85, 599: 75, 600: 70, 601: 90, 602: 80, 603: 59, 604: 99, 605: 89, 606: 60, 607: 85, 608: 50, 609: 75, 610: 65, 611: 35, 612: 45, 613: 80, 614: 45, 615: 55, 616: 105, 617: 67, 618: 85, 619: 125, 620: 70, 621: 115, 622: 80, 623: 85, 624: 145, 625: 103, 626: 133, 627: 45, 628: 65, 629: 62, 630: 82, 631: 40, 632: 60, 633: 40, 634: 60, 635: 50, 636: 70, 637: 95, 638: 40, 639: 50, 640: 75, 641: 50, 642: 63, 643: 50, 644: 65, 645: 85, 646: 50, 647: 70, 648: 60, 649: 45, 650: 105, 651: 45, 652: 70, 653: 50, 654: 70, 655: 80, 656: 50, 657: 60, 658: 91, 659: 131, 660: 70, 661: 95, 662: 115, 663: 40, 664: 70, 665: 80, 666: 55, 667: 75, 668: 55, 669: 60, 670: 90, 671: 60, 672: 70, 673: 90, 674: 40, 675: 80, 676: 30, 677: 85, 678: 40, 679: 84, 680: 50, 681: 60, 682: 90, 683: 50, 684: 80, 685: 70, 686: 100, 687: 95, 688: 50, 689: 75, 690: 75, 691: 105, 692: 66, 693: 112, 694: 50, 695: 70, 696: 90, 697: 55, 698: 65, 699: 129, 700: 90, 701: 72, 702: 70, 703: 80, 704: 70, 705: 70, 706: 100, 707: 120, 708: 90, 709: 90, 710: 90, 711: 100, 712: 90, 713: 90, 714: 90, 715: 77, 716: 90, 717: 95, 718: 65, 719: 95, 720: 122, 721: 40, 722: 58, 723: 72, 724: 40, 725: 52, 726: 67, 727: 38, 728: 77, 729: 43, 730: 55, 731: 71, 732: 40, 733: 60, 734: 50, 735: 58, 736: 72, 737: 39, 738: 47, 739: 68, 740: 48, 741: 62, 742: 62, 743: 78, 744: 60, 745: 54, 746: 76, 747: 76, 748: 100, 749: 150, 750: 50, 751: 150, 752: 60, 753: 72, 754: 66, 755: 86, 756: 53, 757: 88, 758: 67, 759: 115, 760: 60, 761: 90, 762: 62, 763: 88, 764: 33, 765: 52, 766: 77, 767: 119, 768: 50, 769: 72, 770: 65, 771: 75, 772: 57, 773: 150, 774: 35, 775: 53, 776: 70, 777: 91, 778: 48, 779: 76, 780: 70, 781: 70, 782: 70, 783: 70, 784: 122, 785: 122, 786: 122, 787: 122, 788: 85, 789: 184, 790: 35, 791: 80, 792: 95, 793: 95, 794: 121, 795: 150, 796: 110, 797: 60, 798: 60, 799: 120}, 'Sp. Atk': {0: 65, 1: 80, 2: 100, 3: 122, 4: 60, 5: 80, 6: 109, 7: 130, 8: 159, 9: 50, 10: 65, 11: 85, 12: 135, 13: 20, 14: 25, 15: 90, 16: 20, 17: 25, 18: 45, 19: 15, 20: 35, 21: 50, 22: 70, 23: 135, 24: 25, 25: 50, 26: 31, 27: 61, 28: 40, 29: 65, 30: 50, 31: 90, 32: 20, 33: 45, 34: 40, 35: 55, 36: 75, 37: 40, 38: 55, 39: 85, 40: 60, 41: 95, 42: 50, 43: 81, 44: 45, 45: 85, 46: 30, 47: 65, 48: 75, 49: 85, 50: 110, 51: 45, 52: 60, 53: 40, 54: 90, 55: 35, 56: 50, 57: 40, 58: 65, 59: 65, 60: 95, 61: 35, 62: 60, 63: 70, 64: 100, 65: 40, 66: 50, 67: 70, 68: 105, 69: 120, 70: 135, 71: 175, 72: 35, 73: 50, 74: 65, 75: 70, 76: 85, 77: 100, 78: 50, 79: 80, 80: 30, 81: 45, 82: 55, 83: 65, 84: 80, 85: 40, 86: 100, 87: 130, 88: 95, 89: 120, 90: 58, 91: 35, 92: 60, 93: 45, 94: 70, 95: 40, 96: 65, 97: 45, 98: 85, 99: 100, 100: 115, 101: 130, 102: 170, 103: 30, 104: 43, 105: 73, 106: 25, 107: 50, 108: 55, 109: 80, 110: 60, 111: 125, 112: 40, 113: 50, 114: 35, 115: 35, 116: 60, 117: 60, 118: 85, 119: 30, 120: 45, 121: 35, 122: 100, 123: 40, 124: 60, 125: 70, 126: 95, 127: 35, 128: 65, 129: 70, 130: 100, 131: 100, 132: 55, 133: 115, 134: 95, 135: 100, 136: 55, 137: 65, 138: 40, 139: 15, 140: 60, 141: 70, 142: 85, 143: 48, 144: 45, 145: 110, 146: 110, 147: 95, 148: 85, 149: 90, 150: 115, 151: 55, 152: 65, 153: 60, 154: 70, 155: 65, 156: 95, 157: 125, 158: 125, 159: 50, 160: 70, 161: 100, 162: 154, 163: 154, 164: 194, 165: 100, 166: 49, 167: 63, 168: 83, 169: 60, 170: 80, 171: 109, 172: 44, 173: 59, 174: 79, 175: 35, 176: 45, 177: 36, 178: 76, 179: 40, 180: 55, 181: 40, 182: 60, 183: 70, 184: 56, 185: 76, 186: 35, 187: 45, 188: 40, 189: 40, 190: 80, 191: 70, 192: 95, 193: 65, 194: 80, 195: 115, 196: 165, 197: 90, 198: 20, 199: 60, 200: 30, 201: 90, 202: 35, 203: 45, 204: 55, 205: 40, 206: 30, 207: 105, 208: 75, 209: 25, 210: 65, 211: 130, 212: 60, 213: 85, 214: 100, 215: 85, 216: 72, 217: 33, 218: 90, 219: 35, 220: 60, 221: 65, 222: 35, 223: 55, 224: 55, 225: 40, 226: 60, 227: 55, 228: 55, 229: 65, 230: 10, 231: 40, 232: 40, 233: 35, 234: 50, 235: 75, 236: 70, 237: 80, 238: 30, 239: 60, 240: 65, 241: 65, 242: 105, 243: 65, 244: 80, 245: 40, 246: 80, 247: 110, 248: 140, 249: 95, 250: 40, 251: 60, 252: 105, 253: 85, 254: 20, 255: 35, 256: 35, 257: 85, 258: 65, 259: 70, 260: 40, 261: 75, 262: 115, 263: 90, 264: 90, 265: 45, 266: 65, 267: 95, 268: 95, 269: 90, 270: 110, 271: 100, 272: 65, 273: 85, 274: 105, 275: 145, 276: 70, 277: 85, 278: 110, 279: 130, 280: 50, 281: 60, 282: 85, 283: 95, 284: 30, 285: 60, 286: 30, 287: 50, 288: 20, 289: 25, 290: 100, 291: 25, 292: 50, 293: 40, 294: 60, 295: 90, 296: 30, 297: 60, 298: 90, 299: 30, 300: 50, 301: 55, 302: 85, 303: 45, 304: 65, 305: 125, 306: 165, 307: 50, 308: 80, 309: 40, 310: 60, 311: 35, 312: 55, 313: 95, 314: 30, 315: 50, 316: 30, 317: 51, 318: 71, 319: 91, 320: 20, 321: 40, 322: 20, 323: 45, 324: 35, 325: 55, 326: 65, 327: 85, 328: 55, 329: 55, 330: 40, 331: 50, 332: 60, 333: 60, 334: 40, 335: 60, 336: 80, 337: 65, 338: 105, 339: 135, 340: 85, 341: 75, 342: 47, 343: 73, 344: 100, 345: 43, 346: 73, 347: 65, 348: 95, 349: 110, 350: 70, 351: 90, 352: 65, 353: 105, 354: 145, 355: 85, 356: 70, 357: 90, 358: 60, 359: 45, 360: 50, 361: 80, 362: 85, 363: 115, 364: 40, 365: 70, 366: 110, 367: 60, 368: 100, 369: 95, 370: 55, 371: 46, 372: 76, 373: 50, 374: 90, 375: 40, 376: 70, 377: 61, 378: 81, 379: 40, 380: 70, 381: 10, 382: 100, 383: 70, 384: 60, 385: 63, 386: 83, 387: 93, 388: 30, 389: 60, 390: 72, 391: 95, 392: 75, 393: 115, 394: 23, 395: 50, 396: 80, 397: 120, 398: 55, 399: 75, 400: 95, 401: 74, 402: 94, 403: 114, 404: 45, 405: 40, 406: 40, 407: 60, 408: 110, 409: 120, 410: 35, 411: 55, 412: 95, 413: 105, 414: 50, 415: 100, 416: 75, 417: 110, 418: 140, 419: 130, 420: 160, 421: 150, 422: 180, 423: 100, 424: 150, 425: 150, 426: 180, 427: 100, 428: 150, 429: 180, 430: 70, 431: 95, 432: 45, 433: 55, 434: 75, 435: 58, 436: 78, 437: 104, 438: 61, 439: 81, 440: 111, 441: 30, 442: 40, 443: 50, 444: 35, 445: 55, 446: 25, 447: 55, 448: 40, 449: 60, 450: 95, 451: 50, 452: 125, 453: 30, 454: 65, 455: 42, 456: 47, 457: 29, 458: 79, 459: 59, 460: 69, 461: 94, 462: 30, 463: 80, 464: 45, 465: 60, 466: 85, 467: 62, 468: 87, 469: 57, 470: 92, 471: 60, 472: 60, 473: 90, 474: 44, 475: 54, 476: 54, 477: 105, 478: 105, 479: 42, 480: 64, 481: 65, 482: 41, 483: 71, 484: 24, 485: 79, 486: 10, 487: 70, 488: 15, 489: 92, 490: 92, 491: 40, 492: 50, 493: 80, 494: 120, 495: 40, 496: 35, 497: 115, 498: 140, 499: 38, 500: 68, 501: 30, 502: 60, 503: 61, 504: 86, 505: 90, 506: 49, 507: 69, 508: 60, 509: 62, 510: 92, 511: 132, 512: 45, 513: 130, 514: 80, 515: 55, 516: 110, 517: 95, 518: 125, 519: 120, 520: 116, 521: 60, 522: 130, 523: 45, 524: 70, 525: 135, 526: 65, 527: 65, 528: 75, 529: 65, 530: 80, 531: 95, 532: 105, 533: 105, 534: 105, 535: 105, 536: 105, 537: 75, 538: 105, 539: 125, 540: 150, 541: 150, 542: 130, 543: 80, 544: 100, 545: 120, 546: 75, 547: 80, 548: 100, 549: 135, 550: 100, 551: 120, 552: 120, 553: 100, 554: 45, 555: 60, 556: 75, 557: 45, 558: 70, 559: 100, 560: 63, 561: 83, 562: 108, 563: 35, 564: 60, 565: 25, 566: 35, 567: 45, 568: 50, 569: 88, 570: 53, 571: 98, 572: 53, 573: 98, 574: 53, 575: 98, 576: 67, 577: 107, 578: 36, 579: 50, 580: 65, 581: 50, 582: 80, 583: 25, 584: 50, 585: 60, 586: 55, 587: 77, 588: 30, 589: 50, 590: 60, 591: 80, 592: 25, 593: 40, 594: 55, 595: 50, 596: 65, 597: 85, 598: 30, 599: 30, 600: 40, 601: 50, 602: 70, 603: 30, 604: 40, 605: 55, 606: 37, 607: 77, 608: 70, 609: 110, 610: 80, 611: 35, 612: 45, 613: 65, 614: 15, 615: 30, 616: 140, 617: 106, 618: 35, 619: 65, 620: 35, 621: 45, 622: 103, 623: 55, 624: 95, 625: 53, 626: 83, 627: 74, 628: 112, 629: 40, 630: 60, 631: 80, 632: 120, 633: 40, 634: 65, 635: 55, 636: 75, 637: 95, 638: 105, 639: 125, 640: 125, 641: 44, 642: 87, 643: 65, 644: 80, 645: 110, 646: 40, 647: 60, 648: 75, 649: 40, 650: 60, 651: 55, 652: 85, 653: 65, 654: 85, 655: 40, 656: 57, 657: 97, 658: 24, 659: 54, 660: 45, 661: 70, 662: 70, 663: 45, 664: 75, 665: 105, 666: 85, 667: 125, 668: 65, 669: 95, 670: 145, 671: 30, 672: 40, 673: 60, 674: 60, 675: 70, 676: 95, 677: 40, 678: 100, 679: 81, 680: 55, 681: 95, 682: 60, 683: 35, 684: 55, 685: 40, 686: 60, 687: 40, 688: 37, 689: 57, 690: 45, 691: 55, 692: 105, 693: 48, 694: 45, 695: 65, 696: 125, 697: 50, 698: 135, 699: 90, 700: 72, 701: 90, 702: 125, 703: 110, 704: 125, 705: 145, 706: 150, 707: 120, 708: 115, 709: 105, 710: 130, 711: 120, 712: 170, 713: 129, 714: 129, 715: 128, 716: 77, 717: 120, 718: 48, 719: 56, 720: 74, 721: 62, 722: 90, 723: 114, 724: 62, 725: 83, 726: 103, 727: 32, 728: 50, 729: 40, 730: 56, 731: 74, 732: 27, 733: 27, 734: 90, 735: 73, 736: 109, 737: 61, 738: 75, 739: 112, 740: 62, 741: 97, 742: 46, 743: 69, 744: 65, 745: 63, 746: 83, 747: 83, 748: 35, 749: 45, 750: 150, 751: 50, 752: 63, 753: 99, 754: 59, 755: 85, 756: 37, 757: 68, 758: 39, 759: 54, 760: 60, 761: 97, 762: 58, 763: 120, 764: 61, 765: 109, 766: 45, 767: 69, 768: 67, 769: 99, 770: 110, 771: 74, 772: 81, 773: 50, 774: 55, 775: 83, 776: 110, 777: 80, 778: 50, 779: 65, 780: 44, 781: 44, 782: 44, 783: 44, 784: 58, 785: 58, 786: 58, 787: 58, 788: 32, 789: 44, 790: 45, 791: 97, 792: 131, 793: 131, 794: 81, 795: 100, 796: 160, 797: 150, 798: 170, 799: 130}, 'Sp. Def': {0: 65, 1: 80, 2: 100, 3: 120, 4: 50, 5: 65, 6: 85, 7: 85, 8: 115, 9: 64, 10: 80, 11: 105, 12: 115, 13: 20, 14: 25, 15: 80, 16: 20, 17: 25, 18: 80, 19: 80, 20: 35, 21: 50, 22: 70, 23: 80, 24: 35, 25: 70, 26: 31, 27: 61, 28: 54, 29: 79, 30: 50, 31: 80, 32: 30, 33: 55, 34: 40, 35: 55, 36: 85, 37: 40, 38: 55, 39: 75, 40: 65, 41: 90, 42: 65, 43: 100, 44: 25, 45: 50, 46: 40, 47: 75, 48: 65, 49: 75, 50: 90, 51: 55, 52: 80, 53: 55, 54: 75, 55: 45, 56: 70, 57: 40, 58: 65, 59: 50, 60: 80, 61: 45, 62: 70, 63: 50, 64: 80, 65: 40, 66: 50, 67: 90, 68: 55, 69: 70, 70: 95, 71: 95, 72: 35, 73: 60, 74: 85, 75: 30, 76: 45, 77: 70, 78: 100, 79: 120, 80: 30, 81: 45, 82: 65, 83: 65, 84: 80, 85: 40, 86: 80, 87: 80, 88: 55, 89: 70, 90: 62, 91: 35, 92: 60, 93: 70, 94: 95, 95: 50, 96: 100, 97: 25, 98: 45, 99: 35, 100: 55, 101: 75, 102: 95, 103: 45, 104: 90, 105: 115, 106: 25, 107: 50, 108: 55, 109: 80, 110: 45, 111: 65, 112: 50, 113: 80, 114: 110, 115: 110, 116: 75, 117: 45, 118: 70, 119: 30, 120: 45, 121: 105, 122: 40, 123: 80, 124: 100, 125: 25, 126: 45, 127: 50, 128: 80, 129: 55, 130: 85, 131: 120, 132: 80, 133: 95, 134: 85, 135: 85, 136: 70, 137: 90, 138: 70, 139: 20, 140: 100, 141: 130, 142: 95, 143: 48, 144: 65, 145: 95, 146: 95, 147: 110, 148: 75, 149: 55, 150: 70, 151: 45, 152: 70, 153: 75, 154: 95, 155: 110, 156: 125, 157: 90, 158: 85, 159: 50, 160: 70, 161: 100, 162: 90, 163: 100, 164: 120, 165: 100, 166: 65, 167: 80, 168: 100, 169: 50, 170: 65, 171: 85, 172: 48, 173: 63, 174: 83, 175: 45, 176: 55, 177: 56, 178: 96, 179: 80, 180: 110, 181: 40, 182: 60, 183: 80, 184: 56, 185: 76, 186: 35, 187: 55, 188: 20, 189: 65, 190: 105, 191: 45, 192: 70, 193: 45, 194: 60, 195: 90, 196: 110, 197: 100, 198: 50, 199: 80, 200: 65, 201: 100, 202: 55, 203: 65, 204: 95, 205: 55, 206: 30, 207: 85, 208: 45, 209: 25, 210: 65, 211: 95, 212: 130, 213: 42, 214: 110, 215: 85, 216: 48, 217: 58, 218: 65, 219: 35, 220: 60, 221: 65, 222: 65, 223: 65, 224: 95, 225: 40, 226: 60, 227: 55, 228: 80, 229: 100, 230: 230, 231: 95, 232: 105, 233: 75, 234: 50, 235: 75, 236: 40, 237: 80, 238: 30, 239: 60, 240: 85, 241: 35, 242: 75, 243: 45, 244: 140, 245: 70, 246: 50, 247: 80, 248: 90, 249: 95, 250: 40, 251: 60, 252: 95, 253: 65, 254: 45, 255: 35, 256: 110, 257: 65, 258: 55, 259: 55, 260: 70, 261: 135, 262: 100, 263: 75, 264: 115, 265: 50, 266: 70, 267: 100, 268: 120, 269: 154, 270: 154, 271: 100, 272: 55, 273: 65, 274: 85, 275: 85, 276: 50, 277: 60, 278: 70, 279: 80, 280: 50, 281: 70, 282: 90, 283: 110, 284: 30, 285: 60, 286: 41, 287: 61, 288: 30, 289: 25, 290: 50, 291: 25, 292: 90, 293: 50, 294: 70, 295: 100, 296: 30, 297: 40, 298: 60, 299: 30, 300: 50, 301: 30, 302: 70, 303: 35, 304: 55, 305: 115, 306: 135, 307: 52, 308: 82, 309: 60, 310: 60, 311: 35, 312: 55, 313: 65, 314: 30, 315: 50, 316: 30, 317: 23, 318: 43, 319: 73, 320: 30, 321: 60, 322: 40, 323: 90, 324: 35, 325: 55, 326: 65, 327: 115, 328: 55, 329: 95, 330: 40, 331: 50, 332: 60, 333: 80, 334: 55, 335: 75, 336: 85, 337: 40, 338: 60, 339: 80, 340: 75, 341: 85, 342: 75, 343: 75, 344: 80, 345: 53, 346: 83, 347: 20, 348: 40, 349: 65, 350: 35, 351: 45, 352: 45, 353: 75, 354: 105, 355: 70, 356: 80, 357: 110, 358: 60, 359: 45, 360: 50, 361: 80, 362: 40, 363: 60, 364: 75, 365: 105, 366: 105, 367: 60, 368: 60, 369: 85, 370: 65, 371: 41, 372: 71, 373: 35, 374: 55, 375: 70, 376: 120, 377: 87, 378: 107, 379: 50, 380: 80, 381: 55, 382: 125, 383: 70, 384: 120, 385: 33, 386: 63, 387: 83, 388: 90, 389: 130, 390: 87, 391: 80, 392: 60, 393: 60, 394: 48, 395: 50, 396: 80, 397: 80, 398: 50, 399: 70, 400: 90, 401: 55, 402: 75, 403: 75, 404: 65, 405: 65, 406: 30, 407: 50, 408: 80, 409: 90, 410: 60, 411: 80, 412: 90, 413: 110, 414: 100, 415: 200, 416: 150, 417: 130, 418: 150, 419: 110, 420: 120, 421: 140, 422: 160, 423: 90, 424: 90, 425: 90, 426: 100, 427: 100, 428: 50, 429: 20, 430: 160, 431: 90, 432: 55, 433: 65, 434: 85, 435: 44, 436: 52, 437: 71, 438: 56, 439: 76, 440: 101, 441: 30, 442: 40, 443: 60, 444: 40, 445: 60, 446: 41, 447: 51, 448: 34, 449: 49, 450: 79, 451: 70, 452: 105, 453: 30, 454: 50, 455: 88, 456: 138, 457: 45, 458: 105, 459: 85, 460: 95, 461: 50, 462: 42, 463: 102, 464: 90, 465: 30, 466: 50, 467: 53, 468: 78, 469: 62, 470: 82, 471: 66, 472: 44, 473: 54, 474: 56, 475: 96, 476: 96, 477: 105, 478: 52, 479: 37, 480: 59, 481: 50, 482: 41, 483: 61, 484: 86, 485: 116, 486: 45, 487: 90, 488: 65, 489: 42, 490: 108, 491: 45, 492: 55, 493: 85, 494: 95, 495: 85, 496: 40, 497: 70, 498: 70, 499: 42, 500: 72, 501: 55, 502: 75, 503: 40, 504: 65, 505: 72, 506: 61, 507: 86, 508: 120, 509: 60, 510: 85, 511: 105, 512: 85, 513: 90, 514: 95, 515: 55, 516: 50, 517: 85, 518: 95, 519: 115, 520: 56, 521: 65, 522: 95, 523: 75, 524: 60, 525: 75, 526: 115, 527: 115, 528: 150, 529: 135, 530: 70, 531: 77, 532: 107, 533: 107, 534: 107, 535: 107, 536: 107, 537: 130, 538: 105, 539: 70, 540: 100, 541: 120, 542: 106, 543: 110, 544: 120, 545: 100, 546: 130, 547: 80, 548: 100, 549: 90, 550: 100, 551: 75, 552: 120, 553: 100, 554: 55, 555: 75, 556: 95, 557: 45, 558: 55, 559: 65, 560: 45, 561: 60, 562: 70, 563: 39, 564: 69, 565: 45, 566: 65, 567: 90, 568: 37, 569: 50, 570: 48, 571: 63, 572: 48, 573: 63, 574: 48, 575: 63, 576: 55, 577: 95, 578: 30, 579: 42, 580: 55, 581: 32, 582: 63, 583: 25, 584: 40, 585: 80, 586: 43, 587: 55, 588: 45, 589: 65, 590: 86, 591: 126, 592: 35, 593: 50, 594: 65, 595: 40, 596: 55, 597: 75, 598: 85, 599: 75, 600: 60, 601: 80, 602: 80, 603: 39, 604: 79, 605: 69, 606: 50, 607: 75, 608: 50, 609: 75, 610: 55, 611: 35, 612: 45, 613: 70, 614: 45, 615: 55, 616: 105, 617: 67, 618: 35, 619: 75, 620: 70, 621: 115, 622: 80, 623: 65, 624: 105, 625: 45, 626: 65, 627: 45, 628: 65, 629: 62, 630: 82, 631: 40, 632: 60, 633: 40, 634: 60, 635: 65, 636: 85, 637: 110, 638: 50, 639: 60, 640: 85, 641: 50, 642: 63, 643: 60, 644: 75, 645: 95, 646: 50, 647: 70, 648: 60, 649: 45, 650: 105, 651: 55, 652: 80, 653: 85, 654: 105, 655: 45, 656: 50, 657: 60, 658: 86, 659: 116, 660: 60, 661: 85, 662: 85, 663: 40, 664: 70, 665: 80, 666: 55, 667: 95, 668: 55, 669: 60, 670: 90, 671: 40, 672: 50, 673: 70, 674: 40, 675: 80, 676: 135, 677: 65, 678: 60, 679: 99, 680: 50, 681: 60, 682: 90, 683: 50, 684: 80, 685: 40, 686: 70, 687: 95, 688: 50, 689: 75, 690: 65, 691: 95, 692: 66, 693: 48, 694: 50, 695: 70, 696: 90, 697: 55, 698: 105, 699: 72, 700: 90, 701: 129, 702: 80, 703: 90, 704: 80, 705: 80, 706: 120, 707: 100, 708: 80, 709: 80, 710: 90, 711: 90, 712: 100, 713: 90, 714: 90, 715: 128, 716: 77, 717: 95, 718: 45, 719: 58, 720: 75, 721: 60, 722: 70, 723: 100, 724: 44, 725: 56, 726: 71, 727: 36, 728: 77, 729: 38, 730: 52, 731: 69, 732: 25, 733: 30, 734: 50, 735: 54, 736: 66, 737: 79, 738: 98, 739: 154, 740: 57, 741: 81, 742: 48, 743: 71, 744: 90, 745: 60, 746: 81, 747: 81, 748: 37, 749: 49, 750: 50, 751: 150, 752: 65, 753: 89, 754: 57, 755: 75, 756: 46, 757: 75, 758: 56, 759: 86, 760: 60, 761: 123, 762: 63, 763: 89, 764: 43, 765: 94, 766: 45, 767: 59, 768: 63, 769: 92, 770: 130, 771: 63, 772: 67, 773: 150, 774: 75, 775: 113, 776: 150, 777: 87, 778: 60, 779: 82, 780: 55, 781: 55, 782: 55, 783: 55, 784: 75, 785: 75, 786: 75, 787: 75, 788: 35, 789: 46, 790: 40, 791: 80, 792: 98, 793: 98, 794: 95, 795: 150, 796: 110, 797: 130, 798: 130, 799: 90}, 'Speed': {0: 45, 1: 60, 2: 80, 3: 80, 4: 65, 5: 80, 6: 100, 7: 100, 8: 100, 9: 43, 10: 58, 11: 78, 12: 78, 13: 45, 14: 30, 15: 70, 16: 50, 17: 35, 18: 75, 19: 145, 20: 56, 21: 71, 22: 101, 23: 121, 24: 72, 25: 97, 26: 70, 27: 100, 28: 55, 29: 80, 30: 90, 31: 110, 32: 40, 33: 65, 34: 41, 35: 56, 36: 76, 37: 50, 38: 65, 39: 85, 40: 35, 41: 60, 42: 65, 43: 100, 44: 20, 45: 45, 46: 55, 47: 90, 48: 30, 49: 40, 50: 50, 51: 25, 52: 30, 53: 45, 54: 90, 55: 95, 56: 120, 57: 90, 58: 115, 59: 55, 60: 85, 61: 70, 62: 95, 63: 60, 64: 95, 65: 90, 66: 90, 67: 70, 68: 90, 69: 105, 70: 120, 71: 150, 72: 35, 73: 45, 74: 55, 75: 40, 76: 55, 77: 70, 78: 70, 79: 100, 80: 20, 81: 35, 82: 45, 83: 90, 84: 105, 85: 15, 86: 30, 87: 30, 88: 45, 89: 70, 90: 60, 91: 75, 92: 100, 93: 45, 94: 70, 95: 25, 96: 50, 97: 40, 98: 70, 99: 80, 100: 95, 101: 110, 102: 130, 103: 70, 104: 42, 105: 67, 106: 50, 107: 75, 108: 100, 109: 140, 110: 40, 111: 55, 112: 35, 113: 45, 114: 87, 115: 76, 116: 30, 117: 35, 118: 60, 119: 25, 120: 40, 121: 50, 122: 60, 123: 90, 124: 100, 125: 60, 126: 85, 127: 63, 128: 68, 129: 85, 130: 115, 131: 90, 132: 105, 133: 95, 134: 105, 135: 93, 136: 85, 137: 105, 138: 110, 139: 80, 140: 81, 141: 81, 142: 60, 143: 48, 144: 55, 145: 65, 146: 130, 147: 65, 148: 40, 149: 35, 150: 55, 151: 55, 152: 80, 153: 130, 154: 150, 155: 30, 156: 85, 157: 100, 158: 90, 159: 50, 160: 70, 161: 80, 162: 130, 163: 130, 164: 140, 165: 100, 166: 45, 167: 60, 168: 80, 169: 65, 170: 80, 171: 100, 172: 43, 173: 58, 174: 78, 175: 20, 176: 90, 177: 50, 178: 70, 179: 55, 180: 85, 181: 30, 182: 40, 183: 130, 184: 67, 185: 67, 186: 60, 187: 15, 188: 15, 189: 20, 190: 40, 191: 70, 192: 95, 193: 35, 194: 45, 195: 55, 196: 45, 197: 50, 198: 40, 199: 50, 200: 30, 201: 70, 202: 50, 203: 80, 204: 110, 205: 85, 206: 30, 207: 30, 208: 95, 209: 15, 210: 35, 211: 110, 212: 65, 213: 91, 214: 30, 215: 85, 216: 48, 217: 33, 218: 85, 219: 15, 220: 40, 221: 45, 222: 85, 223: 30, 224: 30, 225: 30, 226: 45, 227: 85, 228: 65, 229: 75, 230: 5, 231: 85, 232: 75, 233: 115, 234: 40, 235: 55, 236: 20, 237: 30, 238: 50, 239: 50, 240: 35, 241: 65, 242: 45, 243: 75, 244: 70, 245: 70, 246: 65, 247: 95, 248: 115, 249: 85, 250: 40, 251: 50, 252: 60, 253: 85, 254: 75, 255: 35, 256: 70, 257: 65, 258: 95, 259: 83, 260: 100, 261: 55, 262: 115, 263: 100, 264: 85, 265: 41, 266: 51, 267: 61, 268: 71, 269: 110, 270: 90, 271: 100, 272: 70, 273: 95, 274: 120, 275: 145, 276: 45, 277: 55, 278: 80, 279: 100, 280: 40, 281: 50, 282: 60, 283: 70, 284: 35, 285: 70, 286: 60, 287: 100, 288: 20, 289: 15, 290: 65, 291: 15, 292: 65, 293: 30, 294: 50, 295: 70, 296: 30, 297: 60, 298: 80, 299: 85, 300: 125, 301: 85, 302: 65, 303: 40, 304: 50, 305: 80, 306: 100, 307: 65, 308: 60, 309: 35, 310: 70, 311: 30, 312: 90, 313: 100, 314: 40, 315: 160, 316: 40, 317: 28, 318: 48, 319: 68, 320: 25, 321: 50, 322: 20, 323: 30, 324: 50, 325: 70, 326: 50, 327: 20, 328: 50, 329: 50, 330: 30, 331: 40, 332: 50, 333: 50, 334: 60, 335: 80, 336: 100, 337: 65, 338: 105, 339: 135, 340: 95, 341: 95, 342: 85, 343: 85, 344: 65, 345: 40, 346: 55, 347: 65, 348: 95, 349: 105, 350: 60, 351: 60, 352: 35, 353: 40, 354: 20, 355: 20, 356: 60, 357: 80, 358: 60, 359: 10, 360: 70, 361: 100, 362: 35, 363: 55, 364: 50, 365: 80, 366: 80, 367: 90, 368: 65, 369: 70, 370: 70, 371: 60, 372: 60, 373: 35, 374: 55, 375: 55, 376: 75, 377: 23, 378: 43, 379: 75, 380: 45, 381: 80, 382: 81, 383: 70, 384: 40, 385: 45, 386: 65, 387: 75, 388: 25, 389: 25, 390: 51, 391: 65, 392: 75, 393: 115, 394: 23, 395: 50, 396: 80, 397: 100, 398: 25, 399: 45, 400: 65, 401: 32, 402: 52, 403: 52, 404: 55, 405: 97, 406: 50, 407: 50, 408: 100, 409: 120, 410: 30, 411: 50, 412: 70, 413: 110, 414: 50, 415: 50, 416: 50, 417: 110, 418: 110, 419: 110, 420: 110, 421: 90, 422: 90, 423: 90, 424: 90, 425: 95, 426: 115, 427: 100, 428: 150, 429: 150, 430: 90, 431: 180, 432: 31, 433: 36, 434: 56, 435: 61, 436: 81, 437: 108, 438: 40, 439: 50, 440: 60, 441: 60, 442: 80, 443: 100, 444: 31, 445: 71, 446: 25, 447: 65, 448: 45, 449: 60, 450: 70, 451: 55, 452: 90, 453: 58, 454: 58, 455: 30, 456: 30, 457: 36, 458: 36, 459: 36, 460: 36, 461: 66, 462: 70, 463: 40, 464: 95, 465: 85, 466: 115, 467: 35, 468: 85, 469: 34, 470: 39, 471: 115, 472: 70, 473: 80, 474: 85, 475: 105, 476: 135, 477: 105, 478: 71, 479: 85, 480: 112, 481: 45, 482: 74, 483: 84, 484: 23, 485: 33, 486: 10, 487: 60, 488: 30, 489: 91, 490: 35, 491: 42, 492: 82, 493: 102, 494: 92, 495: 5, 496: 60, 497: 90, 498: 112, 499: 32, 500: 47, 501: 65, 502: 95, 503: 50, 504: 85, 505: 46, 506: 66, 507: 91, 508: 50, 509: 40, 510: 60, 511: 30, 512: 125, 513: 60, 514: 50, 515: 40, 516: 50, 517: 95, 518: 83, 519: 80, 520: 95, 521: 95, 522: 65, 523: 95, 524: 80, 525: 90, 526: 80, 527: 110, 528: 40, 529: 45, 530: 110, 531: 91, 532: 86, 533: 86, 534: 86, 535: 86, 536: 86, 537: 95, 538: 80, 539: 115, 540: 90, 541: 100, 542: 77, 543: 100, 544: 90, 545: 90, 546: 85, 547: 80, 548: 100, 549: 125, 550: 100, 551: 127, 552: 120, 553: 100, 554: 63, 555: 83, 556: 113, 557: 45, 558: 55, 559: 65, 560: 45, 561: 60, 562: 70, 563: 42, 564: 77, 565: 55, 566: 60, 567: 80, 568: 66, 569: 106, 570: 64, 571: 101, 572: 64, 573: 101, 574: 64, 575: 101, 576: 24, 577: 29, 578: 43, 579: 65, 580: 93, 581: 76, 582: 116, 583: 15, 584: 20, 585: 25, 586: 72, 587: 114, 588: 68, 589: 88, 590: 50, 591: 50, 592: 35, 593: 40, 594: 45, 595: 64, 596: 69, 597: 74, 598: 45, 599: 85, 600: 42, 601: 42, 602: 92, 603: 57, 604: 47, 605: 112, 606: 66, 607: 116, 608: 30, 609: 90, 610: 98, 611: 65, 612: 74, 613: 92, 614: 50, 615: 95, 616: 55, 617: 60, 618: 55, 619: 45, 620: 48, 621: 58, 622: 97, 623: 30, 624: 30, 625: 22, 626: 32, 627: 70, 628: 110, 629: 65, 630: 75, 631: 65, 632: 105, 633: 75, 634: 115, 635: 45, 636: 55, 637: 65, 638: 20, 639: 30, 640: 30, 641: 55, 642: 98, 643: 44, 644: 59, 645: 79, 646: 75, 647: 95, 648: 103, 649: 60, 650: 20, 651: 15, 652: 30, 653: 40, 654: 60, 655: 65, 656: 65, 657: 108, 658: 10, 659: 20, 660: 30, 661: 50, 662: 90, 663: 60, 664: 40, 665: 50, 666: 30, 667: 40, 668: 20, 669: 55, 670: 80, 671: 57, 672: 67, 673: 97, 674: 40, 675: 50, 676: 105, 677: 25, 678: 145, 679: 32, 680: 65, 681: 105, 682: 48, 683: 35, 684: 55, 685: 60, 686: 70, 687: 55, 688: 60, 689: 80, 690: 60, 691: 80, 692: 65, 693: 109, 694: 38, 695: 58, 696: 98, 697: 60, 698: 100, 699: 108, 700: 108, 701: 108, 702: 111, 703: 121, 704: 111, 705: 101, 706: 90, 707: 90, 708: 101, 709: 91, 710: 95, 711: 95, 712: 95, 713: 108, 714: 108, 715: 90, 716: 128, 717: 99, 718: 38, 719: 57, 720: 64, 721: 60, 722: 73, 723: 104, 724: 71, 725: 97, 726: 122, 727: 57, 728: 78, 729: 62, 730: 84, 731: 126, 732: 35, 733: 29, 734: 89, 735: 72, 736: 106, 737: 42, 738: 52, 739: 75, 740: 52, 741: 68, 742: 43, 743: 58, 744: 102, 745: 68, 746: 104, 747: 104, 748: 28, 749: 35, 750: 60, 751: 60, 752: 23, 753: 29, 754: 49, 755: 72, 756: 45, 757: 73, 758: 50, 759: 68, 760: 30, 761: 44, 762: 44, 763: 59, 764: 70, 765: 109, 766: 48, 767: 71, 768: 46, 769: 58, 770: 60, 771: 118, 772: 101, 773: 50, 774: 40, 775: 60, 776: 80, 777: 75, 778: 38, 779: 56, 780: 51, 781: 56, 782: 46, 783: 41, 784: 84, 785: 99, 786: 69, 787: 54, 788: 28, 789: 28, 790: 55, 791: 123, 792: 99, 793: 99, 794: 95, 795: 50, 796: 110, 797: 70, 798: 80, 799: 70}, 'Generation': {0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1, 10: 1, 11: 1, 12: 1, 13: 1, 14: 1, 15: 1, 16: 1, 17: 1, 18: 1, 19: 1, 20: 1, 21: 1, 22: 1, 23: 1, 24: 1, 25: 1, 26: 1, 27: 1, 28: 1, 29: 1, 30: 1, 31: 1, 32: 1, 33: 1, 34: 1, 35: 1, 36: 1, 37: 1, 38: 1, 39: 1, 40: 1, 41: 1, 42: 1, 43: 1, 44: 1, 45: 1, 46: 1, 47: 1, 48: 1, 49: 1, 50: 1, 51: 1, 52: 1, 53: 1, 54: 1, 55: 1, 56: 1, 57: 1, 58: 1, 59: 1, 60: 1, 61: 1, 62: 1, 63: 1, 64: 1, 65: 1, 66: 1, 67: 1, 68: 1, 69: 1, 70: 1, 71: 1, 72: 1, 73: 1, 74: 1, 75: 1, 76: 1, 77: 1, 78: 1, 79: 1, 80: 1, 81: 1, 82: 1, 83: 1, 84: 1, 85: 1, 86: 1, 87: 1, 88: 1, 89: 1, 90: 1, 91: 1, 92: 1, 93: 1, 94: 1, 95: 1, 96: 1, 97: 1, 98: 1, 99: 1, 100: 1, 101: 1, 102: 1, 103: 1, 104: 1, 105: 1, 106: 1, 107: 1, 108: 1, 109: 1, 110: 1, 111: 1, 112: 1, 113: 1, 114: 1, 115: 1, 116: 1, 117: 1, 118: 1, 119: 1, 120: 1, 121: 1, 122: 1, 123: 1, 124: 1, 125: 1, 126: 1, 127: 1, 128: 1, 129: 1, 130: 1, 131: 1, 132: 1, 133: 1, 134: 1, 135: 1, 136: 1, 137: 1, 138: 1, 139: 1, 140: 1, 141: 1, 142: 1, 143: 1, 144: 1, 145: 1, 146: 1, 147: 1, 148: 1, 149: 1, 150: 1, 151: 1, 152: 1, 153: 1, 154: 1, 155: 1, 156: 1, 157: 1, 158: 1, 159: 1, 160: 1, 161: 1, 162: 1, 163: 1, 164: 1, 165: 1, 166: 2, 167: 2, 168: 2, 169: 2, 170: 2, 171: 2, 172: 2, 173: 2, 174: 2, 175: 2, 176: 2, 177: 2, 178: 2, 179: 2, 180: 2, 181: 2, 182: 2, 183: 2, 184: 2, 185: 2, 186: 2, 187: 2, 188: 2, 189: 2, 190: 2, 191: 2, 192: 2, 193: 2, 194: 2, 195: 2, 196: 2, 197: 2, 198: 2, 199: 2, 200: 2, 201: 2, 202: 2, 203: 2, 204: 2, 205: 2, 206: 2, 207: 2, 208: 2, 209: 2, 210: 2, 211: 2, 212: 2, 213: 2, 214: 2, 215: 2, 216: 2, 217: 2, 218: 2, 219: 2, 220: 2, 221: 2, 222: 2, 223: 2, 224: 2, 225: 2, 226: 2, 227: 2, 228: 2, 229: 2, 230: 2, 231: 2, 232: 2, 233: 2, 234: 2, 235: 2, 236: 2, 237: 2, 238: 2, 239: 2, 240: 2, 241: 2, 242: 2, 243: 2, 244: 2, 245: 2, 246: 2, 247: 2, 248: 2, 249: 2, 250: 2, 251: 2, 252: 2, 253: 2, 254: 2, 255: 2, 256: 2, 257: 2, 258: 2, 259: 2, 260: 2, 261: 2, 262: 2, 263: 2, 264: 2, 265: 2, 266: 2, 267: 2, 268: 2, 269: 2, 270: 2, 271: 2, 272: 3, 273: 3, 274: 3, 275: 3, 276: 3, 277: 3, 278: 3, 279: 3, 280: 3, 281: 3, 282: 3, 283: 3, 284: 3, 285: 3, 286: 3, 287: 3, 288: 3, 289: 3, 290: 3, 291: 3, 292: 3, 293: 3, 294: 3, 295: 3, 296: 3, 297: 3, 298: 3, 299: 3, 300: 3, 301: 3, 302: 3, 303: 3, 304: 3, 305: 3, 306: 3, 307: 3, 308: 3, 309: 3, 310: 3, 311: 3, 312: 3, 313: 3, 314: 3, 315: 3, 316: 3, 317: 3, 318: 3, 319: 3, 320: 3, 321: 3, 322: 3, 323: 3, 324: 3, 325: 3, 326: 3, 327: 3, 328: 3, 329: 3, 330: 3, 331: 3, 332: 3, 333: 3, 334: 3, 335: 3, 336: 3, 337: 3, 338: 3, 339: 3, 340: 3, 341: 3, 342: 3, 343: 3, 344: 3, 345: 3, 346: 3, 347: 3, 348: 3, 349: 3, 350: 3, 351: 3, 352: 3, 353: 3, 354: 3, 355: 3, 356: 3, 357: 3, 358: 3, 359: 3, 360: 3, 361: 3, 362: 3, 363: 3, 364: 3, 365: 3, 366: 3, 367: 3, 368: 3, 369: 3, 370: 3, 371: 3, 372: 3, 373: 3, 374: 3, 375: 3, 376: 3, 377: 3, 378: 3, 379: 3, 380: 3, 381: 3, 382: 3, 383: 3, 384: 3, 385: 3, 386: 3, 387: 3, 388: 3, 389: 3, 390: 3, 391: 3, 392: 3, 393: 3, 394: 3, 395: 3, 396: 3, 397: 3, 398: 3, 399: 3, 400: 3, 401: 3, 402: 3, 403: 3, 404: 3, 405: 3, 406: 3, 407: 3, 408: 3, 409: 3, 410: 3, 411: 3, 412: 3, 413: 3, 414: 3, 415: 3, 416: 3, 417: 3, 418: 3, 419: 3, 420: 3, 421: 3, 422: 3, 423: 3, 424: 3, 425: 3, 426: 3, 427: 3, 428: 3, 429: 3, 430: 3, 431: 3, 432: 4, 433: 4, 434: 4, 435: 4, 436: 4, 437: 4, 438: 4, 439: 4, 440: 4, 441: 4, 442: 4, 443: 4, 444: 4, 445: 4, 446: 4, 447: 4, 448: 4, 449: 4, 450: 4, 451: 4, 452: 4, 453: 4, 454: 4, 455: 4, 456: 4, 457: 4, 458: 4, 459: 4, 460: 4, 461: 4, 462: 4, 463: 4, 464: 4, 465: 4, 466: 4, 467: 4, 468: 4, 469: 4, 470: 4, 471: 4, 472: 4, 473: 4, 474: 4, 475: 4, 476: 4, 477: 4, 478: 4, 479: 4, 480: 4, 481: 4, 482: 4, 483: 4, 484: 4, 485: 4, 486: 4, 487: 4, 488: 4, 489: 4, 490: 4, 491: 4, 492: 4, 493: 4, 494: 4, 495: 4, 496: 4, 497: 4, 498: 4, 499: 4, 500: 4, 501: 4, 502: 4, 503: 4, 504: 4, 505: 4, 506: 4, 507: 4, 508: 4, 509: 4, 510: 4, 511: 4, 512: 4, 513: 4, 514: 4, 515: 4, 516: 4, 517: 4, 518: 4, 519: 4, 520: 4, 521: 4, 522: 4, 523: 4, 524: 4, 525: 4, 526: 4, 527: 4, 528: 4, 529: 4, 530: 4, 531: 4, 532: 4, 533: 4, 534: 4, 535: 4, 536: 4, 537: 4, 538: 4, 539: 4, 540: 4, 541: 4, 542: 4, 543: 4, 544: 4, 545: 4, 546: 4, 547: 4, 548: 4, 549: 4, 550: 4, 551: 4, 552: 4, 553: 5, 554: 5, 555: 5, 556: 5, 557: 5, 558: 5, 559: 5, 560: 5, 561: 5, 562: 5, 563: 5, 564: 5, 565: 5, 566: 5, 567: 5, 568: 5, 569: 5, 570: 5, 571: 5, 572: 5, 573: 5, 574: 5, 575: 5, 576: 5, 577: 5, 578: 5, 579: 5, 580: 5, 581: 5, 582: 5, 583: 5, 584: 5, 585: 5, 586: 5, 587: 5, 588: 5, 589: 5, 590: 5, 591: 5, 592: 5, 593: 5, 594: 5, 595: 5, 596: 5, 597: 5, 598: 5, 599: 5, 600: 5, 601: 5, 602: 5, 603: 5, 604: 5, 605: 5, 606: 5, 607: 5, 608: 5, 609: 5, 610: 5, 611: 5, 612: 5, 613: 5, 614: 5, 615: 5, 616: 5, 617: 5, 618: 5, 619: 5, 620: 5, 621: 5, 622: 5, 623: 5, 624: 5, 625: 5, 626: 5, 627: 5, 628: 5, 629: 5, 630: 5, 631: 5, 632: 5, 633: 5, 634: 5, 635: 5, 636: 5, 637: 5, 638: 5, 639: 5, 640: 5, 641: 5, 642: 5, 643: 5, 644: 5, 645: 5, 646: 5, 647: 5, 648: 5, 649: 5, 650: 5, 651: 5, 652: 5, 653: 5, 654: 5, 655: 5, 656: 5, 657: 5, 658: 5, 659: 5, 660: 5, 661: 5, 662: 5, 663: 5, 664: 5, 665: 5, 666: 5, 667: 5, 668: 5, 669: 5, 670: 5, 671: 5, 672: 5, 673: 5, 674: 5, 675: 5, 676: 5, 677: 5, 678: 5, 679: 5, 680: 5, 681: 5, 682: 5, 683: 5, 684: 5, 685: 5, 686: 5, 687: 5, 688: 5, 689: 5, 690: 5, 691: 5, 692: 5, 693: 5, 694: 5, 695: 5, 696: 5, 697: 5, 698: 5, 699: 5, 700: 5, 701: 5, 702: 5, 703: 5, 704: 5, 705: 5, 706: 5, 707: 5, 708: 5, 709: 5, 710: 5, 711: 5, 712: 5, 713: 5, 714: 5, 715: 5, 716: 5, 717: 5, 718: 6, 719: 6, 720: 6, 721: 6, 722: 6, 723: 6, 724: 6, 725: 6, 726: 6, 727: 6, 728: 6, 729: 6, 730: 6, 731: 6, 732: 6, 733: 6, 734: 6, 735: 6, 736: 6, 737: 6, 738: 6, 739: 6, 740: 6, 741: 6, 742: 6, 743: 6, 744: 6, 745: 6, 746: 6, 747: 6, 748: 6, 749: 6, 750: 6, 751: 6, 752: 6, 753: 6, 754: 6, 755: 6, 756: 6, 757: 6, 758: 6, 759: 6, 760: 6, 761: 6, 762: 6, 763: 6, 764: 6, 765: 6, 766: 6, 767: 6, 768: 6, 769: 6, 770: 6, 771: 6, 772: 6, 773: 6, 774: 6, 775: 6, 776: 6, 777: 6, 778: 6, 779: 6, 780: 6, 781: 6, 782: 6, 783: 6, 784: 6, 785: 6, 786: 6, 787: 6, 788: 6, 789: 6, 790: 6, 791: 6, 792: 6, 793: 6, 794: 6, 795: 6, 796: 6, 797: 6, 798: 6, 799: 6}, 'Legendary': {0: False, 1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: False, 9: False, 10: False, 11: False, 12: False, 13: False, 14: False, 15: False, 16: False, 17: False, 18: False, 19: False, 20: False, 21: False, 22: False, 23: False, 24: False, 25: False, 26: False, 27: False, 28: False, 29: False, 30: False, 31: False, 32: False, 33: False, 34: False, 35: False, 36: False, 37: False, 38: False, 39: False, 40: False, 41: False, 42: False, 43: False, 44: False, 45: False, 46: False, 47: False, 48: False, 49: False, 50: False, 51: False, 52: False, 53: False, 54: False, 55: False, 56: False, 57: False, 58: False, 59: False, 60: False, 61: False, 62: False, 63: False, 64: False, 65: False, 66: False, 67: False, 68: False, 69: False, 70: False, 71: False, 72: False, 73: False, 74: False, 75: False, 76: False, 77: False, 78: False, 79: False, 80: False, 81: False, 82: False, 83: False, 84: False, 85: False, 86: False, 87: False, 88: False, 89: False, 90: False, 91: False, 92: False, 93: False, 94: False, 95: False, 96: False, 97: False, 98: False, 99: False, 100: False, 101: False, 102: False, 103: False, 104: False, 105: False, 106: False, 107: False, 108: False, 109: False, 110: False, 111: False, 112: False, 113: False, 114: False, 115: False, 116: False, 117: False, 118: False, 119: False, 120: False, 121: False, 122: False, 123: False, 124: False, 125: False, 126: False, 127: False, 128: False, 129: False, 130: False, 131: False, 132: False, 133: False, 134: False, 135: False, 136: False, 137: False, 138: False, 139: False, 140: False, 141: False, 142: False, 143: False, 144: False, 145: False, 146: False, 147: False, 148: False, 149: False, 150: False, 151: False, 152: False, 153: False, 154: False, 155: False, 156: True, 157: True, 158: True, 159: False, 160: False, 161: False, 162: True, 163: True, 164: True, 165: False, 166: False, 167: False, 168: False, 169: False, 170: False, 171: False, 172: False, 173: False, 174: False, 175: False, 176: False, 177: False, 178: False, 179: False, 180: False, 181: False, 182: False, 183: False, 184: False, 185: False, 186: False, 187: False, 188: False, 189: False, 190: False, 191: False, 192: False, 193: False, 194: False, 195: False, 196: False, 197: False, 198: False, 199: False, 200: False, 201: False, 202: False, 203: False, 204: False, 205: False, 206: False, 207: False, 208: False, 209: False, 210: False, 211: False, 212: False, 213: False, 214: False, 215: False, 216: False, 217: False, 218: False, 219: False, 220: False, 221: False, 222: False, 223: False, 224: False, 225: False, 226: False, 227: False, 228: False, 229: False, 230: False, 231: False, 232: False, 233: False, 234: False, 235: False, 236: False, 237: False, 238: False, 239: False, 240: False, 241: False, 242: False, 243: False, 244: False, 245: False, 246: False, 247: False, 248: False, 249: False, 250: False, 251: False, 252: False, 253: False, 254: False, 255: False, 256: False, 257: False, 258: False, 259: False, 260: False, 261: False, 262: True, 263: True, 264: True, 265: False, 266: False, 267: False, 268: False, 269: True, 270: True, 271: False, 272: False, 273: False, 274: False, 275: False, 276: False, 277: False, 278: False, 279: False, 280: False, 281: False, 282: False, 283: False, 284: False, 285: False, 286: False, 287: False, 288: False, 289: False, 290: False, 291: False, 292: False, 293: False, 294: False, 295: False, 296: False, 297: False, 298: False, 299: False, 300: False, 301: False, 302: False, 303: False, 304: False, 305: False, 306: False, 307: False, 308: False, 309: False, 310: False, 311: False, 312: False, 313: False, 314: False, 315: False, 316: False, 317: False, 318: False, 319: False, 320: False, 321: False, 322: False, 323: False, 324: False, 325: False, 326: False, 327: False, 328: False, 329: False, 330: False, 331: False, 332: False, 333: False, 334: False, 335: False, 336: False, 337: False, 338: False, 339: False, 340: False, 341: False, 342: False, 343: False, 344: False, 345: False, 346: False, 347: False, 348: False, 349: False, 350: False, 351: False, 352: False, 353: False, 354: False, 355: False, 356: False, 357: False, 358: False, 359: False, 360: False, 361: False, 362: False, 363: False, 364: False, 365: False, 366: False, 367: False, 368: False, 369: False, 370: False, 371: False, 372: False, 373: False, 374: False, 375: False, 376: False, 377: False, 378: False, 379: False, 380: False, 381: False, 382: False, 383: False, 384: False, 385: False, 386: False, 387: False, 388: False, 389: False, 390: False, 391: False, 392: False, 393: False, 394: False, 395: False, 396: False, 397: False, 398: False, 399: False, 400: False, 401: False, 402: False, 403: False, 404: False, 405: False, 406: False, 407: False, 408: False, 409: False, 410: False, 411: False, 412: False, 413: False, 414: True, 415: True, 416: True, 417: True, 418: True, 419: True, 420: True, 421: True, 422: True, 423: True, 424: True, 425: True, 426: True, 427: True, 428: True, 429: True, 430: True, 431: True, 432: False, 433: False, 434: False, 435: False, 436: False, 437: False, 438: False, 439: False, 440: False, 441: False, 442: False, 443: False, 444: False, 445: False, 446: False, 447: False, 448: False, 449: False, 450: False, 451: False, 452: False, 453: False, 454: False, 455: False, 456: False, 457: False, 458: False, 459: False, 460: False, 461: False, 462: False, 463: False, 464: False, 465: False, 466: False, 467: False, 468: False, 469: False, 470: False, 471: False, 472: False, 473: False, 474: False, 475: False, 476: False, 477: False, 478: False, 479: False, 480: False, 481: False, 482: False, 483: False, 484: False, 485: False, 486: False, 487: False, 488: False, 489: False, 490: False, 491: False, 492: False, 493: False, 494: False, 495: False, 496: False, 497: False, 498: False, 499: False, 500: False, 501: False, 502: False, 503: False, 504: False, 505: False, 506: False, 507: False, 508: False, 509: False, 510: False, 511: False, 512: False, 513: False, 514: False, 515: False, 516: False, 517: False, 518: False, 519: False, 520: False, 521: False, 522: False, 523: False, 524: False, 525: False, 526: False, 527: False, 528: False, 529: False, 530: False, 531: False, 532: False, 533: False, 534: False, 535: False, 536: False, 537: True, 538: True, 539: True, 540: True, 541: True, 542: True, 543: True, 544: True, 545: True, 546: False, 547: False, 548: False, 549: True, 550: True, 551: True, 552: True, 553: True, 554: False, 555: False, 556: False, 557: False, 558: False, 559: False, 560: False, 561: False, 562: False, 563: False, 564: False, 565: False, 566: False, 567: False, 568: False, 569: False, 570: False, 571: False, 572: False, 573: False, 574: False, 575: False, 576: False, 577: False, 578: False, 579: False, 580: False, 581: False, 582: False, 583: False, 584: False, 585: False, 586: False, 587: False, 588: False, 589: False, 590: False, 591: False, 592: False, 593: False, 594: False, 595: False, 596: False, 597: False, 598: False, 599: False, 600: False, 601: False, 602: False, 603: False, 604: False, 605: False, 606: False, 607: False, 608: False, 609: False, 610: False, 611: False, 612: False, 613: False, 614: False, 615: False, 616: False, 617: False, 618: False, 619: False, 620: False, 621: False, 622: False, 623: False, 624: False, 625: False, 626: False, 627: False, 628: False, 629: False, 630: False, 631: False, 632: False, 633: False, 634: False, 635: False, 636: False, 637: False, 638: False, 639: False, 640: False, 641: False, 642: False, 643: False, 644: False, 645: False, 646: False, 647: False, 648: False, 649: False, 650: False, 651: False, 652: False, 653: False, 654: False, 655: False, 656: False, 657: False, 658: False, 659: False, 660: False, 661: False, 662: False, 663: False, 664: False, 665: False, 666: False, 667: False, 668: False, 669: False, 670: False, 671: False, 672: False, 673: False, 674: False, 675: False, 676: False, 677: False, 678: False, 679: False, 680: False, 681: False, 682: False, 683: False, 684: False, 685: False, 686: False, 687: False, 688: False, 689: False, 690: False, 691: False, 692: False, 693: False, 694: False, 695: False, 696: False, 697: False, 698: False, 699: True, 700: True, 701: True, 702: True, 703: True, 704: True, 705: True, 706: True, 707: True, 708: True, 709: True, 710: True, 711: True, 712: True, 713: False, 714: False, 715: False, 716: False, 717: False, 718: False, 719: False, 720: False, 721: False, 722: False, 723: False, 724: False, 725: False, 726: False, 727: False, 728: False, 729: False, 730: False, 731: False, 732: False, 733: False, 734: False, 735: False, 736: False, 737: False, 738: False, 739: False, 740: False, 741: False, 742: False, 743: False, 744: False, 745: False, 746: False, 747: False, 748: False, 749: False, 750: False, 751: False, 752: False, 753: False, 754: False, 755: False, 756: False, 757: False, 758: False, 759: False, 760: False, 761: False, 762: False, 763: False, 764: False, 765: False, 766: False, 767: False, 768: False, 769: False, 770: False, 771: False, 772: False, 773: False, 774: False, 775: False, 776: False, 777: False, 778: False, 779: False, 780: False, 781: False, 782: False, 783: False, 784: False, 785: False, 786: False, 787: False, 788: False, 789: False, 790: False, 791: False, 792: True, 793: True, 794: True, 795: True, 796: True, 797: True, 798: True, 799: True}}
)

# Vizualizando os dados carregados



1.   head(n) -> mostra as [n] primeiras linhas do dataframe
2.   tail(n) -> mostra as [n] ultimas linhas do dataframe
3.   info() -> informações sobre as colunas do dataframe
4.   describe() -> informações estatísticas sobre as colunas do dataframe (apenas colunas com dados numéricos)

In [ ]:
pokemon.head(8)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False

In [ ]:
pokemon.shape

(800, 13)

In [ ]:
pokemon.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int64
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 82.0+ KB

In [ ]:
pokemon.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

# Limpando e organizando os dados



*   drop_duplicates(keep=first\last, subset='nome_da_coluna') -> remove linhas com dados duplicados, utilizando a opção keep, pode-se manter o primeiro ou o último dado duplicado

*   sort_values(by='nome_da_coluna', ascendig=True/False) -> reorganiza todo o dataframe a partir de uma coluna, do menor ao maior, ou do maior ao menor com [ascending=False]
*   groupby(by='nome_da_coluna') -> agrupa uma certa coluna, juntando todos os valores semelhantes desta coluna e os "guardando" para que sucessivamente se utilize de metodos estatísticos como mean(), sum(). Desta forma o grupo de valores repetidos

In [ ]:
# todos os valores duplicados da coluna [#] são removidos,
# exceto a primeira ocasião
pokemon.drop_duplicates(keep='first', subset='#')

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [ ]:
pokemon.dropna()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [ ]:
pokemon.sort_values(by='Name')

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,494,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,310,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,465,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,510,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,330,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,245,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,420,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True

In [ ]:
pokemon.sort_values(by='Defense', ascending=False)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False
224,208,SteelixMega Steelix,Steel,Ground,610,75,125,230,55,95,30,2,False
333,306,AggronMega Aggron,Steel,NaN,630,70,140,230,60,80,50,3,False
223,208,Steelix,Steel,Ground,510,75,85,200,55,65,30,2,False
414,377,Regirock,Rock,NaN,580,80,100,200,50,100,50,3,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,63,Abra,Psychic,NaN,310,25,20,15,105,55,90,1,False
186,172,Pichu,Electric,NaN,205,20,40,15,35,35,60,2,False
261,242,Blissey,Normal,NaN,540,255,10,10,75,135,55,2,False
488,440,Happiny,Normal,NaN,220,100,5,5,15,65,30,4,False
121,113,Chansey,Normal,NaN,450,250,5,5,35,105,50,1,False

In [ ]:
gb = pokemon.loc[:,'Type 1':"Speed"].groupby('Type 1').mean()

round(gb, 2)

           Total     HP  Attack  Defense  Sp. Atk  Sp. Def   Speed
Type 1
Bug       378.93  56.88   70.97    70.72    53.87    64.80   61.68
Dark      445.74  66.81   88.39    70.23    74.65    69.52   76.16
Dragon    550.53  83.31  112.12    86.38    96.84    88.84   83.03
Electric  443.41  59.80   69.09    66.30    90.02    73.70   84.50
Fairy     413.18  74.12   61.53    65.71    78.53    84.71   48.59
Fighting  416.44  69.85   96.78    65.93    53.11    64.70   66.07
Fire      458.08  69.90   84.77    67.77    88.98    72.21   74.44
Flying    485.00  70.75   78.75    66.25    94.25    72.50  102.50
Ghost     439.56  64.44   73.78    81.19    79.34    76.47   64.34
Grass     421.14  67.27   73.21    70.80    77.50    70.43   61.93
Ground    437.50  73.78   95.75    84.84    56.47    62.75   63.91
Ice       433.46  72.00   72.75    71.42    77.54    76.29   63.46
Normal    401.68  77.28   73.47    59.85    55.82    63.72   71.55
Poison    399.14  67.25   74.68    68.82    60.43    64.39   63.57
Psychic   475.95  70.63   71.46    67.68    98.40    86.28   81.49
Rock      453.75  65.36   92.86   100.80    63.34    75.48   55.91
Steel     487.70  65.22   92.70   126.37    67.52    80.63   55.26
Water     430.46  72.06   74.15    72.95    74.81    70.52   65.96

In [ ]:
type2nan = pokemon['Type 2'].copy()
type2nan.fillna('', inplace=True)

pokemon['Mt'] = pokemon['Type 1'] + ' ' + type2nan
pokemon = pokemon.reindex(columns=['#', 'Name', 'Type 1', 'Type 2', 'Mt',
                                   'Total', 'HP', 'Attack', 'Defense',
                                   'Sp. Atk', 'Sp. Def', 'Speed', 'Generation',
                                   'Legendary'])
pokemon

,#,Name,Type 1,Type 2,Mt,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,Grass Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,Grass Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,Grass Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,Grass Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,Fire,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,Rock Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,Rock Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,Psychic Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,Psychic Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,Fire Water,600,80,110,120,130,90,70,6,True

In [ ]:
gb = pokemon.loc[:,'Mt':"Speed"].groupby('Mt').mean()
round(gb, 2)

Total      418.0
HP          57.5
Attack      82.5
Defense     92.5
Sp. Atk     40.0
Sp. Def     92.5
Speed       53.0
Name: Dark Fighting, dtype: float64

In [ ]:
gb.loc['Dark Fighting']

Total      418.0
HP          57.5
Attack      82.5
Defense     92.5
Sp. Atk     40.0
Sp. Def     92.5
Speed       53.0
Name: Dark Fighting, dtype: float64

In [ ]:
gb.loc['Fighting Dark']

Total      495.0
HP          95.0
Attack     124.0
Defense     78.0
Sp. Atk     69.0
Sp. Def     71.0
Speed       58.0
Name: Fighting Dark, dtype: float64

In [ ]:
type2nan = pokemon['Type 2'].copy()
type2nan.fillna('', inplace=True)

pokemon.loc[pokemon['Type 1'] < pokemon['Type 2'], 'Mt'] = pokemon['Type 1'] + ' ' + type2nan
pokemon.loc[pokemon['Type 1'] > pokemon['Type 2'], 'Mt'] = type2nan + ' ' + pokemon['Type 1']

pokemon = pokemon.reindex(columns=['#', 'Name', 'Type 1', 'Type 2', 'Mt',
                                   'Total', 'HP', 'Attack', 'Defense',
                                   'Sp. Atk', 'Sp. Def', 'Speed', 'Generation',
                                   'Legendary'])

In [ ]:
gb = pokemon.loc[:,'Mt':"Speed"].groupby('Mt').mean()
gb = round(gb, 2)

In [ ]:
qtype = 'Fire'.capitalize()
qstatus = 'speed'.capitalize()
mask = pokemon.loc[(pokemon['Type 1'] == qtype) | (pokemon['Type 2'] == qtype)]
mask.sort_values(by=qstatus, ascending=False).head(10)

,#,Name,Type 1,Type 2,Mt,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
731,663,Talonflame,Fire,Flying,Fire Flying,499,78,81,71,74,69,126,6,False
248,229,HoundoomMega Houndoom,Dark,Fire,Dark Fire,600,75,90,90,140,90,115,2,False
437,392,Infernape,Fire,Fighting,Fighting Fire,534,76,104,71,104,71,108,4,False
736,668,Pyroar,Fire,Normal,Fire Normal,507,86,68,72,109,66,106,6,False
84,78,Rapidash,Fire,NaN,NaN,500,65,100,70,80,80,105,1,False
723,655,Delphox,Fire,Psychic,Fire Psychic,534,75,69,72,114,100,104,6,False
573,514,Simisear,Fire,NaN,NaN,498,75,98,63,98,63,101,5,False
263,244,Entei,Fire,NaN,NaN,580,115,115,85,90,75,100,2,True
698,637,Volcarona,Bug,Fire,Bug Fire,550,85,60,65,135,105,100,5,False
171,157,Typhlosion,Fire,NaN,NaN,534,78,84,78,109,85,100,2,False